### ISSUE TITLE
Status summary plots

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#1]
Need to script more status summary plots
- a) Total assembled, tested, grade A/B/C vs. date 
  Done, but no data yet
  http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/test_modulegrapher.php
- b) Same as a), but split by assembly site 
  Done, but no data yet
  http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/test_modulegrapher.php?loc=purdue
  http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/test_modulegrapher.php?loc=nebraska
- c) Same as a) and b), but as fractions, not absolute numbers
- d) Total tested, grade A/B/C vs. date
- e) Same as d), but as fractions
- f) Total B or C, bad due to IV, bad due to bad channels vs. date
- g) Same as f), but as fractions
- h) Total assembled, total x-rayed, problematic x-ray(?)
  Need definition of what x-ray problems could be
- i) plot all IV curves of all modules, at 17C, into one plot
- j) same as i), but at -20C

**Comment by khan62** [comment]
Now that there is enough data for these graphs to be populated, here is a graph for point f):

http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/bad_modulegrapher.php

The three lines are assembled, bad IV, and bad bumps. If more grading criteria are added I can include those as well.

**Comment by khan62** [comment]
These graphs are now available as Module Quality Graphs from the main menu.
