### ISSUE TITLE
missing plots in full test summary page

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#10]
I uploaded an xml file today for module P-A-3-34, and many plots are missing from the module summary page, for example dist_TrimMap_C7_V0.png.

**Comment by khan62** [comment]
Can you email me your input?

**Comment by jstupak** [comment]
I can't track down the zip file that was uploaded.  But I see it again with this zip:

http://home.fnal.gov/~jstupak/files/P-A-3-41.zip

**Comment by khan62** [comment]
I tried uploading just the config files, and it looks like they all got uploaded without a problem. I think the issue (as well as issue #11) might be that the page is timing out because of how many files there are.

**Comment by khan62** [comment]
I think this can be solved by using MoReWeb. Most (if not all) of the pictures you're trying to upload are parsed and displayed through MoReWeb. I'm not sure about the config files, but if they're the only things being uploaded, the page shouldn't hang up. If you still want to add the picture files, my only suggestion would be to parse it out into several smaller uploads.

**Comment by jstupak** [comment]
I'll bring this up, but im not sure its going to fly.  The timeout period can't be extended?

**Comment by khan62** [comment]
Purdue's IT department is very conservative about making changes to the webservers. I have asked them on a number of occasions for changes and updates and never gotten anywhere. It is effectively impossible to extend the timeout period.

**Comment by jstupak** [comment]
Would uploading 2 or more separate zip files per module help?

**Comment by khan62** [comment]
It would solve the issue of the timeout. However, I want to encourage MoReWeb as a solution to this problem, as it is better suited for parsing and displaying this data than a simple list.
