### ISSUE TITLE
When are modules labelled "assembled"?

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#105]
I see from the graph on the main page that 4 modules are assembled, but from the talks today it sounds like only 1 has really been assembled.  Based on the assembly status page, I am guessing that modules are counted as assembled after the HDI is attached, regardless of whether the wire bonding, etc. has been performed.  Is this really what we want?  I would think post-encapsulation would be better

**Comment by khan62** [comment]
Modules are considered "bare" until an HDI is attached, at which point it is considered "assembled".

**Comment by jstupak** [comment]
sounds like we are fine with the current implementation
