### ISSUE TITLE
DB upload issue

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#106]
I am unable to upload results to the DB.  I get a message saying:

"Not all fields were filled, please retry"

on this page:

http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/batchallsubmit.php?code=2

It appears I am able to upload to moreweb, getting this message:

"The data is uploaded and ready to be parsed"

but I have not verified that the upload was successful (waiting for cron job).

Is this expected given the issue that was mentioned during today's meeting?

**Comment by khan62** [comment]
That message should only appear if the user did not enter their username or did not enter a file to be uploaded. It shouldn't be related to the MoReWeb issue.

**Comment by jstupak** [comment]
Ah, I misinterpreted "Not all fields were filled, please retry" to mean there was a problem with parsing and only some of the DB fields were filled.  Shifters probably won't make this mistake, but could we make the error message a bit more specific?  If this is a generic error message on many pages, then forget it.

I put in my name and uploaded the results for P-Z-2-02.  The page said it was fine, but I don't see the info on the module's full test summary page.  Some info must have made it bc the IV grade is a B, but what happened to the rest?

Also, still don't see the moreweb results.  Is this expected?

On a separate note, can I put the shifter's name in master.xml to avoid them having to do it?  I know I have asked before, but I forgot the answer.

**Comment by NickHinton** [comment]
Greg is working on this issue now. We're not ignoring you John, I promise!

**Comment by gneeser** [comment]
Both MoReWeb and the batch submit have been successfully tested over here. Let me know if you encounter any more problems. 

Also, I changed the error message to be a little more descriptive.

**Comment by NickHinton** [comment]
I tried to use the batch submit a bit ago for modules M-H-2-15, M-H-2-02, and M-H-1-03, but it doesn't look like the data was added to any of them.

**Comment by gneeser** [comment]
Consolidated Batch Submit is working again.
