### ISSUE TITLE
Slight change in workflow on Assembly Status page needed

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#107]
On the page http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/status.php in the module table, it would be good to move the two columns 'Thermally Cycled' and 'Tested' to after 'Shipped', since this is now done at Fermilab only. 

Thanks,
Petra

**Comment by merkelp** [comment]
by the way, the order should also be changed for the check boxes on the individual module pages to reflect the correct workflow.

**Comment by khan62** [comment]
I believe those boxes are specifically for that testing if/when it's done at Purdue. I think the functionality you're looking for is encapsulated by the "Post-Assembly" testing flags on the Full Summary page.
