### ISSUE TITLE
Bare Module Plot for M-H-1-03

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#108]
I just uploaded the bare module IV for M-H-1-03, but the displayed data doesn't make sense. What's going on?

**Comment by NickHinton** [comment]
Module M-H-1-06 has the same problem. 

Both are TT sensors....a clue?

**Comment by khan62** [comment]
I think I found the issue.

In the Bare Module IV scan for M-H-1-03, at 120V the total current is 0. That can't be displayed on a log scale, so the graph bugged out. Is this something we expect to happen often enough to set a check for values equal to 0?

**Comment by NickHinton** [comment]
No, it isn't something we expect often. We're currently plotting the 'total' current for the bare module IV, but we also have 'active' and 'guard' currents. We would like to plot 'active' + 'guard' instead of total. 

BUT, Nebraska will only have 'total' currents.  So we want to plot those, only if there are no 'active' and 'guard' currents.

Does that change request make sense? I mentioned it to Greg, but never put it in an Issue.

**Comment by NickHinton** [comment]
Also the change in the values we plot would be only for the bare module IV, not for on-wafer or assembled modules.

**Comment by khan62** [comment]
All of the xmlgrapher files now substitute 1E-10 for zero values that would otherwise break the log scale. Also, for the bare module IVs they first check if ACTV_CURRENT_AMP and GRD_CURRENT_AMP exist, and if either does not, it uses TOT_CURRENT_AMP instead.
