### ISSUE TITLE
Remove Preproduction Module Results from MoreWeb

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#109]
We should remove the test results for preproduction modules from MoreWeb. We should also remove M-F-2-02, because it is incorrectly named.

**Comment by NickHinton** [comment]
We also need to change the HDI listed as 'on module' that are attached to preproduction modules.

**Comment by gneeser** [comment]
Preproduction modules have been hidden on MoReWeb.

**Comment by gneeser** [comment]
M-F-2-02 has also been removed.
