### ISSUE TITLE
broken config file button

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#11]
When I click the config files button on the full test summary page, I get the following error:

Warning: opendir(../module_config_files/171) [function.opendir]: failed to open dir: No such file or directory in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/configfiles.php on line 49
File        Size        Timestamp

**Comment by jstupak** [comment]
Link: 

http://www.physics.purdue.edu/cmsfpix/Submission_p/download/configfiles.php?name=M_FR_915

**Comment by khan62** [comment]
That error showed up because there were no config files to be displayed. I have fixed the error so that it now just shows the empty page (With the file, size, and timestamp headers). Were you expecting output on this page specifically? That might be a bug related to issue #10.

**Comment by jstupak** [comment]
Thanks Kamal!

I think this is probably not related to #10.  I probably just never uploaded configs for this module :)

**Comment by jstupak** [comment]
You were right, this issue does appear connected with #10.  I see no config files with this zip:

http://home.fnal.gov/~jstupak/files/P-A-3-41.zip

**Comment by khan62** [comment]
I'm going to close this thread because the primary discussion is occuring on #10
