### ISSUE TITLE
moreweb broken again?

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#110]
We tried to upload moreweb results for M-H-1-04 and M-H-1-48 about 15 minutes ago, but we do not see the results yet.  We think the cron job is supposed to run every 5, so we should haev seen the results by now.  Is moreweb broken again?

**Comment by NickHinton** [comment]
We've checked, and it is not the permissions issue that was a problem last week.

I also can't see results from a module I just tested. We will resolve this as soon as we can.

**Comment by NickHinton** [comment]
....and as soon as I comment the results show up...looks like the issue is fixed. Let me know if you encounter any more problems John.

**Comment by jstupak** [comment]
Thanks!

**Comment by NickHinton** [comment]
We're digging into this issue, but for now it looks like MoreWeb results take longer to show up on the page than expected. My last upload took ~40 minutes to show up.

**Comment by gneeser** [comment]
MoReWeb is now updating at normal speeds.
