### ISSUE TITLE
M-G-2-25 Incorrect HDI Attached

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#111]
When promoting module BL_CR_126 to assembled we attached it to the wrong HDI. We attached it to YFC89-3815-2-35, when it was actually attached to YFC84-3915-2-35.

Can someone fix this?

**Comment by khan62** [comment]
I should have it taken care of in the next 10 minutes

**Comment by khan62** [comment]
I changed:
times_HDI_p on_module value for both HDIs
HDI_p module and assembly values for both HDIs
module_p assoc_HDI value for the module

If I forgot anything let me know
