### ISSUE TITLE
Bigger legend text, axis labels in IV curves

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#112]
Hi all,

Would it be easy to blow up the text in the IV plots?  In his presentation just now, @NickHinton had to tell us which color was which IV because the legend on actual the IV plot is woefully undersized.

Thanks,

Jamie

**Comment by gneeser** [comment]
I increased the size of the text in the legend and axis titles:

http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/xmlgrapher.php?id=2246&scan=IV&level=module

**Comment by lantone** [comment]
looks fabulous, thanks!  if you wanted to crank it up even a bit more, i wouldn't be opposed to it...
