### ISSUE TITLE
temperature field

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#113]
Can we please add a field for the temperature as measured by the RTD on the module during testing at FNAL?  This field should be searchable.  Thanks!

**Comment by gneeser** [comment]
John, 
Before I get started, I'd like to double-check what you'd like to make sure I understand.

My understanding is that you want to know the temperature of the module at the end of the -20C Full Test. First of all, is that correct? 

Second, where do you want it to be displayed? The Full Test Summary page?

Third, we need to get the info to the DB. The way that I see this happening is through an additional xml tag in the Consolidated Batch Submit file. It would probably have to be within the <TEST> tag, similar to the <CAN_TIME> tag and others we've used before. 

The only difficulty I foresee is that if we have a single scalar describing the temperature, it would be overridden each time a new full test was uploaded. The DB doesn't really know what kind of test is being run, so the best way to go about it would be to only include that tag for tests where you want the temperature to be recorded. 

So, the way that I think it would work: when you run a test where you want the temperature as measured by the RTD to be recorded in the DB, include a tag in a structure something like this:

<TEST>
    <NAME>M_CR_923</NAME>
    <UNMASKABLE_PIX>42</UNMASKABLE_PIX>
    <UNADDRESSABLE_PIX>51</UNADDRESSABLE_PIX>
    <CAN_TIME>1</CAN_TIME>
    **<RTD_TEMP>-20</RTD_TEMP>**
    <NOTES>THESE ARE TEST NOTES</NOTES>
    <ROCS>
         .............
    </ROCS>
</TEST>

How does that sound? Am I on the right track of what you're looking for?

**Comment by jstupak** [comment]
Hello Greg,

My understanding is that you want to know the temperature of the module at the end of the -20C Full Test. First of all, is that correct?

Correct.

Second, where do you want it to be displayed? The Full Test Summary page?

Sounds good.

Third, we need to get the info to the DB. The way that I see this happening is through an additional xml tag in the Consolidated Batch Submit file. It would probably have to be within the <TEST> tag, similar to the <CAN_TIME> tag and others we've used before.

Sounds good.

The only difficulty I foresee is that if we have a single scalar describing the temperature, it would be overridden each time a new full test was uploaded. The DB doesn't really know what kind of test is being run, so the best way to go about it would be to only include that tag for tests where you want the temperature to be recorded.

We only plan to upload test results once per module, for the tests done here at FNAL at -20C.  So I think this is not a problem, if I understand you correctly.

So, the way that I think it would work: when you run a test where you want the temperature as measured by the RTD to be recorded in the DB, include a tag in a structure something like this:

<TEST>
<NAME>M_CR_923</NAME>
<UNMASKABLE_PIX>42</UNMASKABLE_PIX>
<UNADDRESSABLE_PIX>51</UNADDRESSABLE_PIX>
<CAN_TIME>1</CAN_TIME>
<RTD_TEMP>-20</RTD_TEMP>
<NOTES>THESE ARE TEST NOTES</NOTES>
<ROCS>
.............
</ROCS>
</TEST>

That looks fine.

How does that sound? Am I on the right track of what you're looking for?

Sounds perfect to me!  Thanks.

Regards,
John

##########################
John Stupak III

Postdoctoral Research Associate
Purdue University Calumet
jstupak@fnal.govmailto:jstupak@fnal.gov
508-254-5387
skype: JohnStupak
##########################

On Jan 5, 2016, at 1:13 PM, gneeser <notifications@github.com<mailto:notifications@github.com>> wrote:

John,
Before I get started, I'd like to double-check what you'd like to make sure I understand.

My understanding is that you want to know the temperature of the module at the end of the -20C Full Test. First of all, is that correct?

Second, where do you want it to be displayed? The Full Test Summary page?

Third, we need to get the info to the DB. The way that I see this happening is through an additional xml tag in the Consolidated Batch Submit file. It would probably have to be within the <TEST> tag, similar to the <CAN_TIME> tag and others we've used before.

The only difficulty I foresee is that if we have a single scalar describing the temperature, it would be overridden each time a new full test was uploaded. The DB doesn't really know what kind of test is being run, so the best way to go about it would be to only include that tag for tests where you want the temperature to be recorded.

So, the way that I think it would work: when you run a test where you want the temperature as measured by the RTD to be recorded in the DB, include a tag in a structure something like this:

<TEST>
<NAME>M_CR_923</NAME>
<UNMASKABLE_PIX>42</UNMASKABLE_PIX>
<UNADDRESSABLE_PIX>51</UNADDRESSABLE_PIX>
<CAN_TIME>1</CAN_TIME>
<RTD_TEMP>-20</RTD_TEMP>
<NOTES>THESE ARE TEST NOTES</NOTES>
<ROCS>
.............
</ROCS>
</TEST>

How does that sound? Am I on the right track of what you're looking for?

**Comment by gneeser** [comment]
John,
The DB now looks for the tag <RTD_TEMP> when unpacking xml's, located inside the <TEST> tag. It should be a number with no other characters, otherwise it won't upload successfully. 

I successfully tested it using a test module and xml, but let me know if things don't update correctly. 

For modules that have already been uploaded, I can add the numbers manually if you'd like - or I can add a field in Manual Update so that it can be done from your end.

The temperature as measured by the RTD can also be searched for on the Tested Modules List page.

**Comment by jstupak** [comment]
Hello Greg,

Im working on adding this to our script.  When you say "a number with no other characters", do you mean that "-20" would be a problem since it contains "-"?

**Comment by gneeser** [comment]
Sorry that wasn't clear. The minus sign is fine, I just meant that "-20C" or something like that would cause a problem.

**Comment by jstupak** [comment]
Hello Greg, We are now uploading this data and everything looks good.  Thanks!
