### ISSUE TITLE
can not see module pages

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#114]
Hi,
since the outage last night was restored I can not see individual module full test summary pages like this: http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-H-2-35 anymore. I already cleared the cookies and cache. Is anyone else having this problem or am I the only one? Any ideas?

Thanks,
Petra

**Comment by NickHinton** [comment]
I have the same problem. We are looking into it now.

**Comment by gneeser** [comment]
The issue should be resolved now.

**Comment by merkelp** [comment]
yes, it works, thanks!
