### ISSUE TITLE
Can't Promote Module M-H-2-23 to Encapsulated

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#115]
When we try (with all visible fields filled in) it resets all the fields to blank and does not update the status of the module.

**Comment by gneeser** [comment]
You should be able to promote to encapsulated now. You will not be able to promote to "Ready for Shipping" yet though. I'll post when I fix that step.

**Comment by gneeser** [comment]
Module assembly flow will proceed as normal now. However, we won't be able to promote a module to 'Ready for Shipping" without going through encapsulation and post-encapsulation testing (though you can still skip straight to shipped). That capacity will have to be implemented at a later date.
