### ISSUE TITLE
module disappeared 

### ISSUE THREAD

**Issue by rbartek** [puhep/pudb#117]
module M-H-2-07 is no longer on the parts assembly list after I changed the status to tested. i can find it on the database, but it is no longer on the assembly flow

Also the status shows as tested (post thermal cycling).  This module has not been thermal cycled.

**Comment by NickHinton** [comment]
Hi Rachel,

This issue is related to how we're changing the part assembly flow to accommodate doing all thermal cycling at Fermilab now. I know Greg has been working on smoothing out the transition, but there is still a bit of work to be done. We'll see about clearing this up.

**Comment by gneeser** [comment]
Rachel,
I made a change and put a test module through without issue. Let me know if you have any more problems with it. In the meantime, I manually moved M-H-2-07 back to the post-encapsulation testing bin.

**Comment by NickHinton** [comment]
I promoted two modules from encapsulated to tested without any trouble after Greg's change, so I'm going to close this issue.
