### ISSUE TITLE
FNAL IV results @17C

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#119]
Hey Greg,

We need to be able to upload the results of the 17C IV scan ran here at FNAL to the Purdue DB. Also, on the IV by position page we need to have a total plot for the 17C and -20C IV results. The latter is already there, the plot needs to say it's at -20C so we can differentiate it from the 17C results.

Doug

**Comment by gneeser** [comment]
Doug,

I've made the DB able to handle both the -20C and +17C results. To upload the -20C results, the <SCAN> tag should have the <LEVEL> "fnal" as before. For the +17C scan, it should have a <LEVEL> of "fnal_17c" 

The plots have also been updated accordingly. 

This required a lot of little changes, so it's possible I missed something. Let me know if you catch any problems.

-Greg

**Comment by drberry85** [comment]
John,

I have no idea how to test if this is working. Would it be simple-ish to
make the uploadTest.py script handle 17C and -20C IV results? In theory the
17C IV results should be done before the -20, but sometimes they'll be done
at UNL and we won't have access to the data. We may have to make two
seperate uploads. One for the 17C results and one for the -20C.

Thoughts?
Doug

**Comment by jstupak** [comment]
The latter option you mentioned is definitely the way to go.  We have the shifters run uploadTest for 17 and -20 tests anyway (to move the elCom output to the production area).  So I'll just add a command line option that controls whether all the usual results get zipped, or just the IV.  Then modify the twiki to instruct shifters to upload the zip file after each test.

**Comment by gneeser** [comment]
I did run a test using a simple zip that I made. You can see the result on the part summary pages for P-A-test3-test3 and P-A-test2-test2,  some of the database testing modules I made a while back. If you turn show preproduction on, you can also see them on the +17C plot on the IV by Position page. They have the same data, so they'll overlap, but they're both there.

**Comment by jstupak** [comment]
It looks to me like we can close this now

**Comment by gneeser** [comment]
Will do then. Let me know if you encounter any problems with it later.
