### ISSUE TITLE
x-ray slope and offset search

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#12]
The x-ray slope and offset are stored for each ROC.  How does the search work for these parameters?

**Comment by khan62** [comment]
Previously it was still searching on a per-module basis. It now searches for the values stored per-ROC, and a module will be displayed if any of its ROCs pass the filter. Does this work, or do you want the filter to limit them such that the module is only displayed if all ROCs pass the filter?

**Comment by jstupak** [comment]
I think your current implementation is probably fine, but lets bring it up at the next Monday meeting

**Comment by jstupak** [comment]
we discussed the search capability and we are happy with the current implementation
