### ISSUE TITLE
consolidated batch submit error

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#120]
We just tried to upload some results to the DB, but got the following error message:

An error has occurred and the comment has not been addedJpGraph Error: 25121 Empty input data array specified for plot. Must have at least one data point.

I made some changes to our code yesterday, so it could be my fault.  But the xml files (master and the IV) look fine to me.  The zip is available in my lxplus public dir:

/afs/cern.ch/user/j/jstupak/public/M-G-3-03_FPIXTest_m20C_FNAL_2016_01_06__14_14_2016-01-06_14h14m_1452111295.zip

Could you please take a look and see if you think the problem is on my end or yours?

**Comment by gneeser** [comment]
John, 
I tested Consolidated Batch Submit on my end and didn't get any problems. Have you been able to upload other results since then?

I have to admit, I'm not sure what an Ixplus public directory is, or how to get there... could you send the zip to me as an attachment in an email? Or is it too large?

**Comment by jstupak** [comment]
Greg,

I think you should have access to this:

https://drive.google.com/file/d/0B-Sb2-PyA4oHTnNJUzBxVUxhZHM/view?usp=sharing

**Comment by gneeser** [comment]
I do, thanks. I'll take a look and see if I can find anything.

**Comment by gneeser** [comment]
John,
It looks like the <NAME> tag in the xml is what's going wrong. In the xml you gave me, it has the test name:
M-G-3-03_FPIXTest_m20C_FNAL_2016_01_06__14_14_2016-01-06_14h14m_1452111295
In the <NAME> tag. The database tries to treat this as a module name, so of course it doesn't find a module that has that name. 

I edited the xml, changing the name in the <TEST> tag, and tried resubmitting it, which allowed all of the ROC values to update, but not the pictures or the IV. 

Changing the xml such that it's made with the module name in the <NAME> tag should fix our problem, then.

**Comment by jstupak** [comment]
This did indeed fix the problem.  Thanks!
