### ISSUE TITLE
moreweb upload not working

### ISSUE THREAD

**Issue by rbartek** [puhep/pudb#121]
Hi

I tried to upload a new result for M-H-1-23 but it doesn't appear on the database. Is there only one MoReWeb results per modules allowed?

**Comment by jstupak** [comment]
Yes, until we fix the names of the tests so they are unique.  I should push a fix for this tomorrow to the FPIXUtils and elComandante repos.

In the meantime, if you need to review the results there is a way to access them.  Go to the page which contains the results that are accessible.  The address should be something like:

http://www.physics.purdue.edu/cmsfpix/MoReWeb/Results/REV001/R001/M-H-1-03_ElComandanteTest_2015-12-15_14h45m_1450212335/QualificationGroup/ModuleFPIXTest_m20_1/TestResult.html

Then replace: "M-H-1-03_ElComandanteTest_2015-12-15_14h45m_1450212335/QualificationGroup/ModuleFPIXTest_m20_1"

With the analogous string for the other test you want to access.  

Skype me if thats not clear.

**Comment by NickHinton** [comment]
Hi John and Rachel,

Is this issue resolved? If so I'll close it.

Thanks,
Nick

**Comment by rbartek** [comment]
I think so
On Jan 22, 2016, at 4:22 PM, NickHinton <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi John and Rachel,

Is this issue resolved? If so I'll close it.

Thanks,
Nick
