### ISSUE TITLE
Setting 'X Ray Tested' Flag via xml

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb#123]
I've heard that people have been looking for the ability to set the X Ray Tested post-assembly testing flag through the xml upload. There are two ways I could go about this. 

First, I could have the database set the flag any time that x ray results are uploaded, but that would not be negotiable (i.e. you couldn't upload x-ray results and not have the flag changed). 

Second, I could require a specific tag, maybe <XRAY_TESTED> under <TEST> in the same way we have <CAN_TIME> and the new <RTD_TEMP> tag.

Do either of those options sound like what you guys are looking for?

**Comment by jstupak** [comment]
Making sure @roberts42 and @isando3 see this.

IMO the latter option is better.  It gives us flexibility and is not hard to add to the xray upload script.  But I'll let the x-ray guys decide

**Comment by isando3** [comment]
I agree with John

**Comment by gneeser** [comment]
Alright, then I'll let you all know when I have that ready.

**Comment by gneeser** [comment]
I added the check for the new tag. It expects the tag to be <XRAY_TESTED> (1 for true) and under the <TEST> tag

**Comment by gneeser** [comment]
Have you all tested this feature? If it's working, we can close the issue, but if you encounter any problems, let me know.
