### ISSUE TITLE
Bug in 'More Files' Page for Module Test Data

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#124]
When I click on the 'more files' link for test data for a given module I see a series of errors. The particular page in question is at:

http://www.physics.purdue.edu/cmsfpix/Submission_p/download/XMLfiles.php?part=module&partid=1350&scan=IV

The error messages are:

Warning: simplexml_load_string() [function.simplexml-load-string]: Entity: line 1: parser error : Start tag expected, '<' not found in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 49

Warning: simplexml_load_string() [function.simplexml-load-string]: # IV test from Fri, 08 Jan 2016 14:00:28 CST +172859000 nsec in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 49

Warning: simplexml_load_string() [function.simplexml-load-string]: ^ in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 49

Notice: Trying to get property of non-object in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 50

Notice: Trying to get property of non-object in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 50

Notice: Trying to get property of non-object in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 50

Notice: Trying to get property of non-object in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 51

Notice: Trying to get property of non-object in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 51

Notice: Trying to get property of non-object in /net/copernicus/project1/cmsfpix/.www/Submission_p/download/XMLfiles.php on line 51

**Comment by gneeser** [comment]
Nick,
It looks like there was a log file uploaded in place of an xml file. There errors are the result of trying to parse a text file as an xml. It doesn't seem to be a problem with the database itself.
