### ISSUE TITLE
One more column in module status table

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#125]
Hello,

I think it would be useful if we could add one more column in http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/status.php after 'Ready for mounting', namely modules that are in state 'Rejected' (next testing step).
Then it would be easier to add things up and know how many modules we can forget about and how many we can still have hope for during debugging/testing.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
I've added a "Rejected" column on the assembly status page. It is a new assembly step, so the number of rejected modules has been subtracted automatically from the number of shipped modules. It's still set the same way, through the next testing step.

-Greg
