### ISSUE TITLE
Bug somewhere in module counting?

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#126]
Hi,
when I look at the module summary table at http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/status.php I see a total of 96 modules, 60 of which are still at the assembly sites in the various stages of assembly, and 36 have been shipped out and tested.

But when I look at the plot on http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php (and also the corresponding module lists on that page) I only get 35 modules as shipped.

I did not have the time to investigate which module is missing from this, but maybe someone else could find the time?

Cheers,
Petra

**Comment by gneeser** [comment]
Petra,
The issue was with M-G-3-06 due to the abnormal manual promotion sequence - because we couldn't bond it, we manually promoted it and I forgot one of the associated fields. I have since updated the field and the numbers match up.

-Greg

**Comment by merkelp** [comment]
Great, thanks, Greg!
