### ISSUE TITLE
Additional module location option of "In Transit"

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#127]
Hi @gneeser ,
    I was just discussing with John and Doug here, we agree it'd be useful to add an option of "In Transit" for the "Current Location" of a module.  At the moment rely on comments on an individual module page, but being able to view all the modules in transit via the Tested Modules List would help us organize our shifting manpower a couple of days in advance.
   It seems straightforward from where I sit (easy for me to say), but do you foresee any complications with adding another location option?

Thanks,

Jamie

**Comment by gneeser** [comment]
Jamie,
It will take a little doing, but I don't foresee any problems as of now. I'll keep you posted if anything comes up.

-Greg

**Comment by lantone** [comment]
another (arguably better) option:  just a boolean for "In Transit?", set to true when shipped and back to false when received.  That way the "Current Location" would be free to be used to denote the destination of modules when in transit.

**Comment by gneeser** [comment]
Jamie,
I added a yes/no filter option for in transit. Does this match what you were looking for?

-Greg

**Comment by lantone** [comment]
yeah, that's perfect.  but now how do i mark a module as being in transit?

**Comment by gneeser** [comment]
Promoting it to shipped takes care of that.

**Comment by lantone** [comment]
but what if it's shipped multiple times?  like a module that goes from UNL->KU->FNAL?  once's it's "shipped" once can it be somehow promoted again?

**Comment by gneeser** [comment]
That's a good point, I hadn't thought of that. I added a checkbox on the Update Module Location page for 'In transit.' Just check that and update the location to the destination; when it arrives, you can update the location as normal.

**Comment by lantone** [comment]
Awesome! Thanks Greg!

**Comment by gneeser** [comment]
My pleasure!
