### ISSUE TITLE
ROC grade bug

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#128]
It looks like there is a bug here:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-B-7-22

It says:

Grades that were not A: 
ROC5: Grade B; biggest contribution: 85 bad bumps

But it is actually ROC10 that has 85 bad bumps.  

@lantone pointed out that ROCs 10 and 5 are directly across from one another, so maybe somehow ROC 8 is getting mapped to 7, 9 to 6, 10 to 5, ...

**Comment by lantone** [comment]
here's another instance in which it appears the ROC number is getting flipped vertically:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-B-4-44

**Comment by gneeser** [comment]
Found and fixed the bug.

-Greg
