### ISSUE TITLE
More filter options

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#129]
Hello,

on http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php we have the filter options of the flags (17C, -20C, xray, thermal cycle). It would be very useful to have the opposite option, namely to filter by which step has NOT YET been checked. 
It would be very nice to have now that we are getting more and more modules.
But it is slightly less urgent than Marco's plot :)

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
I've added the opposite option. Nick and I checked it over, but let me know if you find any issues.

-Greg
