### ISSUE TITLE
ROC fields

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#13]
I now see the changes that were made to the handling of ROCs to accommodate per-ROC data: 

<ROC><POSITION>2</POSITION><IS_DEAD>1</IS_DEAD><XRAY_OFFSET>3.141</XRAY_OFFSET><XRAY_SLOPE>1.413</XRAY_SLOPE></ROC>

Does this mean I also have to change how I specify which ROCs are dead/alive, or the changes were backwards compatible?

**Comment by jstupak** [comment]
github mangled the XML I pasted in and converted it to 213.1411.413, but you know what I mean :)

**Comment by khan62** [comment]
The changes are backwards compatible with the <DEAD_ROCS> and <LIVE_ROCS> tags. You can use the <ROC> tag to specify the xray slope and offset and the <DEAD/LIVE_ROCS> tags to specify live/dead ROCS if you wish.
