### ISSUE TITLE
Marco's Plot

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#130]
Hi
  we need one more plot (a single one) in the Purdue DB. This plot should
contain the following information
- number of bump bonded modules delivered by RTI
- number of modules past the assembly stage (in my mind this is
  the number of modules that have been shipped out from Nebraska
  and Purdue)
- number of modules that have passed the qualification stage (i.e. after
  thermal cycling, X-ray, and testing at Fermilab, even if the X-ray step
  has been skipped)
- number of modules that are suitable for installation.

This plot should essentially be a mashup of plots that we already have in
the Purdue DB, and it shouldn't be too complicated to add it.

An example of this plot is attached below (this plot is for the total of the 
BPIX production). This plot is complicated by the fact that for BPIX they
do the additional bare module test (and declare modules as being good bare modules). The 4 categories that I mentioned above are the ones listed
as "bump bonded", "assembled", "qualified", and "detector grade" in the BPIX
plot. I would like to use exactly the same terminology in our plot. The BPIX
plot has a fixed vertical scale with lines that say "install" (this line would be 
at 672 in our case", and spares (this line would be at 940 in our case). BPIX 
has an horizontal axis that indicates the weeks in calendar year 2014 and 2015,
with some arbitrary dates that say "mechanics complete", and "end of mounting".
In our case the "end of mounting" date could be taken as 30 Jun 2016....

This plot is a request from the tracker management and they want to be 
able to show it on a weekly basis to the management of CMS....

Would it be possible to implement this ? It can also be done it outside of the Purdue DB just sucking the data from there....  (I already have a script of my
own to get the number of A, B, and C grade modules without clicking too much).

![2b8f8511-324f-4e3c-b0c5-08d8f6aea2ca](https://cloud.githubusercontent.com/assets/12564567/12524653/94f8af20-c12c-11e5-952d-f47d6ba17a82.png)

**Comment by gneeser** [comment]
Here's what I have so far:

http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/module_summary_grapher.php

Anything you all can see that needs to be changed or added?

**Comment by gneeser** [comment]
The two plots, linear and logarithmic, are live on the site:
http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/time.php?

-Greg
