### ISSUE TITLE
IV bug?

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#131]
What exactly happened with the assembled module scan here?

http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/xmlgrapher.php?id=1855&scan=IV&level=module

**Comment by gneeser** [comment]
Looking at the xml file that plot is based on, it doesn't seem to be a database issue - it's just plotting the points in the file. 

I'm not sure what could have happened to cause the scan to behave like that, though I do see that this is one of the modules where the guard ring current hit compliance in the bare module IV.

**Comment by jstupak** [comment]
@xshi any idea what happened during the scan, or who might have done the scan?

**Comment by gneeser** [comment]
I did the bare module scan, and I believe Nick did the assembled module test.

**Comment by jstupak** [comment]
Thanks Greg. 

@NickHinton any idea what happened?

**Comment by NickHinton** [comment]
Nope. Might have been a bug with our IV code. Have you seen any other instances of this behavior?

**Comment by jstupak** [comment]
Nope.  I too was wondering if this was a one-off, or something else.  I guess we can close the issue until we see it again?

**Comment by NickHinton** [comment]
Yes. I'm closing the issue. If anyone sees a similar result down the line we will re-open it.
