### ISSUE TITLE
adding "Final Judgement" option to "Next Testing Step"

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#134]
Hi Greg,
   The problem with solving all our problems so fast is that then we think of new ones :-)
   Could you add a "Final Judgement" option for the "Next Testing Step" whenever you get a chance?  The use case is modules for which the x-ray testing is the final testing step.  We don't expect the x-ray shifters at UIC to know what should happen next (Rejected vs. Ready for Mounting), but we don't want the Next Testing Step to remain "X-ray Testing" after they complete that step.
Thanks,
Jamie

**Comment by gneeser** [comment]
Jamie,
I added the step. Let me know if you encounter any problems with it.

-Greg
