### ISSUE TITLE
A modules misgraded as B

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#135]
Hey Greg and John,

It looks like LessWeb is grading grade A modules as grade B because it's looking at the total number of bad bump bonds instead of the bad bumps per ROC. Examples are [M-B-4-44](http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-B-4-44) and [M-G-2-48](http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-G-2-48). These are grade A modules, but it looks like LessWeb is saying they are grade B because they have 44 bad bumps and 83 bad bumps, respectively. While this does place a single ROC pass the 0.1% threshold, these bumps are distributed across multiple ROCs. You can check in MoReWeb and see that [M-B-4-44](http://www.physics.purdue.edu/cmsfpix/MoReWeb/Results/REV001/R001/M-B-4-44_FPIXTest-m20C-FNAL-160125-1241_2016-01-25_12h41m_1453747305/QualificationGroup/ModuleFPIXTest_m20_1/TestResult.html) and [M-G-2-48](http://www.physics.purdue.edu/cmsfpix/MoReWeb/Results/REV001/R001/M-G-2-48_FPIXTest-m20C-FNAL-160121-1344_2016-01-21_13h45m_1453405526/QualificationGroup/ModuleFPIXTest_m20_1/TestResult.html) should be grade a modules.

Doug

**Comment by jstupak** [comment]
These grades look correct to me.  ROC 13 on M-B-4-44 has 48 (44+4) defects, which is over the 1% threshold, so B is correct grade.

**Comment by lantone** [comment]
I agree with @jstupak, our pixel grades are used to assign ROC grades, and then the module is assigned a grade equal to the worst ROC grade.  So, at least with the current system, there's no cross-talk between defects on different ROCs.

**Comment by lantone** [comment]
The DB/MoReWeb discrepancy comes from the bump bonding analysis done in MoReWeb [1].  In the latest commits from @gfunk723 this issue has been addressed.  Once we do an update on Purdue's side (in the coming days) everything should be consistent.

Hey, I just had a thought - MoReWeb is like the cross-check analysis that never gets officially used but helps the mainline analysis validation its analysis code!

[1] http://www.physics.purdue.edu/cmsfpix/MoReWeb/Results/REV001/R001/M-B-4-44_FPIXTest-m20C-FNAL-160125-1241_2016-01-25_12h41m_1453747305/QualificationGroup/ModuleFPIXTest_m20_1/Chips/Chip13/TestResult.html#CMSPixel_QualificationGroup_Fulltest_Chips_Chip_BumpBonding_TestResult_BumpBonding

**Comment by gneeser** [comment]
With the new update of MoReWeb a few days back, has this discrepancy been resolved?

**Comment by lantone** [comment]
yes indeed!  44 = 44:

MoReWeb:
http://www.physics.purdue.edu/cmsfpix/MoReWeb/Results/REV001/R001/M-B-4-44_FPIXTest-m20C-FNAL-160125-1241_2016-01-25_12h41m_1453747305/QualificationGroup/ModuleFPIXTest_m20_1/Chips/Chip13/TestResult.html#d

LessWeb:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-B-4-44

**Comment by gneeser** [comment]
Excellent!
