### ISSUE TITLE
x-ray test results

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#14]
I uploaded a first set of x-ray tests:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M_TT_922

But I dont know how to check if the slope and offset fields were set correctly.  Can you please check this?

**Comment by khan62** [comment]
I added a table to that page of the X-Ray offset values. If that looks ok, I can do the same with the slope as well

**Comment by jstupak** [comment]
Thanks!  looks good to me

**Comment by khan62** [comment]
Tables are now displayed for both offset and slope values
