### ISSUE TITLE
mismatch on test_list.php

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#140]
Hello,

I am looking right now on the tested modules list page, where there are 95 modules listed. These should be all the 'shipped' modules. But the black curve in the plot looks more like 94 modules to me.
And if I look at the assembly status page, I see shipped+ready+rejected=94 modules. 

Any idea where this additional module is coming from? An impostor?

Thanks,
Petra

**Comment by gneeser** [comment]
Looks like it was a naming issue. The pages now match. There are 147 matching modules on the tested modules list page, and on the assembly page 62+38+47=147.
