### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rbartek** [puhep/pudb#143]
tried to upload log file

Notice: Undefined index: part in /net/hooke/project0/cmsfpix/.www/Submission_p/summary/summaryfile_proc.php on line 8

Notice: Undefined index: id in /net/hooke/project0/cmsfpix/.www/Submission_p/summary/summaryfile_proc.php on line 8

Warning: Cannot modify header information - headers already sent by (output started at /net/hooke/project0/cmsfpix/.www/Submission_p/summary/summaryfile_proc.php:8) in /net/hooke/project0/cmsfpix/.www/Submission_p/summary/summaryfile_proc.php on line 10

**Comment by gneeser** [comment]
Which part was this for? Also, can you send me the file you were trying to upload?

**Comment by rbartek** [comment]
Log file in upload file for module. Details not with me

Sent from my iPhone

On 11 Feb 2016, at 2:02 PM, gneeser <notifications@github.com<mailto:notifications@github.com>> wrote:

Which part was this for? Also, can you send me the file you were trying to upload?

**Comment by NickHinton** [comment]
@rbartek are you still having problems with this?

**Comment by rbartek** [comment]
Still Doesn’t work. Pxar log files can’t be added with “add Extra File to This Par” button?
On Feb 16, 2016, at 2:18 PM, NickHinton <notifications@github.com<mailto:notifications@github.com>> wrote:

@rbartekhttps://github.com/rbartek are you still having problems with this?

**Comment by gneeser** [comment]
Rachel,
I've tested this several times on several modules and haven't had a problem, for example here:
http://www.physics.purdue.edu/cmsfpix/Submission_p/download/configfiles.php?name=M-I-2-37

Can you tell me what part you're having trouble with? Or is it multiple parts?

-Greg
