### ISSUE TITLE
can not upload to MoreWeb right now

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#149]
Hi, nothing is showing up since almost an hour. Any ideas what's going on?

Thanks,
Petra

**Comment by NickHinton** [comment]
I just spoke with Chris and MoReWeb was humming along. It was processing the M-J-1-37 FPix test at -20 C, which finished a minute or two ago.

Are you still having problems?

**Comment by merkelp** [comment]
Hi Nick,
yes, got it, just took unusually long.

Thanks for checking,
Petra
