### ISSUE TITLE
bottons overlaid on images

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#15]
There is a minor issue related to the "update", "config files", etc buttons showing up on top of images.  You can see what I mean here:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M_LL_914

**Comment by khan62** [comment]
Thanks, I didn't realize the picture array ever got wide enough to infringe on the buttons. I'll try moving them above the pictures

**Comment by khan62** [comment]
Is their position now ok? Do you also want them below the pictures?

**Comment by jstupak** [comment]
I definitely like this new position.  But it might be nice to have them at the bottom as well, if its trivial for you

**Comment by khan62** [comment]
No problem at all
