### ISSUE TITLE
M-H-2-35 missing from modulereport.csv

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#151]
Hi,

Nick recently pointed me to the "Module Report" feature as requested by Lenny in #17 

For some reason, this module is not being included in the resulting csv file:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-H-2-35

Any ideas why?

Thanks,

Jamie

**Comment by NickHinton** [comment]
I noticed that Kamal fixed the HDI attached to this module manually, maybe that's a clue? Just thinking out loud...

**Comment by NickHinton** [comment]
Yep, that was the problem. The 'module' field in the HDI was set to 0. It's fixed now.
