### ISSUE TITLE
Int instead of float in submitfunctions.php for Xray Eff and Unif? 

### ISSUE THREAD

**Issue by isando3** [puhep/pudb#153]
Hi,

Seems like the values for LOW_DC_HIGHRATE_EFF, LOW_DC_LOWRATE_EFF, LOW_DC_UNI and HIGH_DC_UNI are being stored as integers. Can we display those as floats with 3 precision digits? 

Thanks

**Comment by gneeser** [comment]
I changed the data type of the fields you mentioned to float, so it will record whatever precision is uploaded for the moment. Did you want three digits to the right of the decimal, or just three digits total?

Also, it looks like the data for the modules with have to be uploaded again because the database didn't store anything past an integer. 

-Greg

**Comment by isando3** [comment]
Thanks Greg,

Ok, I will reupload those results

On Tue, Mar 1, 2016 at 4:00 PM, gneeser notifications@github.com wrote:

> I changed the data type of the fields you mentioned to float, so it will
> record whatever precision is uploaded for the moment. Did you want three
> digits to the right of the decimal, or just three digits total?
> 
> Also, it looks like the data for the modules with have to be uploaded
> again because the database didn't store anything past an integer.
> 
> -Greg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puhep/pudb/issues/153#issuecomment-190924617.

## 

_Best Regards,_

---

_Daniel SandovalUniversity of Illinois at ChicagoPhysics Department *
*Office: SES 2156, Lab: SES 2259_
_Office   Phone: (+1) (312)-996-5648_
_email:  isando3@uic.edu isando3@uic.edu_
- ```
         isandova@cern.ch <isandova@cern.ch>*
  ```
- ```
         dansand@fnal.gov <dansand@fnal.gov>
  ```
  
  ---

**Comment by gneeser** [comment]
Let me know how the uploads go. If there are no problems, we can close the issue.

-Greg

**Comment by isando3** [comment]
You can close it. It seems to be fine now.

Thanks a lot

On Thu, Mar 3, 2016 at 10:08 AM, gneeser notifications@github.com wrote:

> Let me know how the uploads go. If there are no problems, we can close the
> issue.
> 
> -Greg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puhep/pudb/issues/153#issuecomment-191829353.

## 

_Best Regards,_

---

_Daniel SandovalUniversity of Illinois at ChicagoPhysics Department *
*Office: SES 2156, Lab: SES 2259_
_Office   Phone: (+1) (312)-996-5648_
_email:  isando3@uic.edu isando3@uic.edu_
- ```
         isandova@cern.ch <isandova@cern.ch>*
  ```
- ```
         dansand@fnal.gov <dansand@fnal.gov>
  ```
  
  ---

**Comment by gneeser** [comment]
No problem!

-Greg
