### ISSUE TITLE
M-J-4-11

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#154]
Hello,
I just received M-J-4-11 from KU and moved it to Fermilab in the DB. It does not show up on the tested modules page, although its status is 'shipped' and the next testing step is set to 'thermal cycling'. The only other weird thing I see is that the ROC numbers are not listed on the part summary page.

Thanks for looking into it.
Petra

**Comment by NickHinton** [comment]
I found and resolved the issue. M-J-4-11 now shows up on the tested modules page and has ROCs associated it. The lack of ROCs was the problem.

@rbartek do you know why there were no ROCs associated to this module? Was it not uploaded via the batch upload?
