### ISSUE TITLE
Test results didn't show on the lessweb

### ISSUE THREAD

**Issue by chenxvan** [puhep/pudb#155]
Hi,

I submitted the test results for M-J-4-38 twice today, but none of them shows on the lessweb. 

Here is the info shows on the lessweb:
**2016-03-02 12:54:44 Test results and config files can be found in: M-J-4-38_FPIXTest-17C-FNAL-160302-1009_2016-03-02_10h09m_1456934972
2016-03-02 14:18:35 Test results and config files can be found in: M-J-4-38_FPIXTest-17C-FNAL-160302-1009_2016-03-02_10h09m_1456934972

No pictures for this part**

Moreweb works fine for this module. Should I try to re-submit it to lessweb later?

Thanks

Xuan

**Comment by gneeser** [comment]
Did you try re-submitting the data via lessWeb? I see results on the Full Test Summary page: 
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-J-4-38
-Greg

**Comment by drberry85** [comment]
Greg,

The calibration results on LessWeb are ones from FNAL.

Doug

**Comment by chenxvan** [comment]
Hi Greg,

No, I didn't resubmit the data. It seems the lessweb takes longer time to process the data. 

Hi Doug, the results i was talking about is the full test results from FNAL. 

Thanks!
Xuan
