### ISSUE TITLE
Inconsistent IV summary plots

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#156]
Hi,
the plots here: http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/pos.php
are not consistent with each other. It would be good to fill the plots for the sensors of the different positions with the same data as the top plot. Right now 2 modules are in the top most plot that are failing the 2uA@150V criterion, but I can not see from the plots below of which type they are.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
The IV by Position now uses only the -20C FNAL scans (excepting the +17C plot, of course). 

Best,
Greg
