### ISSUE TITLE
User field in recently updated modules list

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#16]
Can we please add a user name for test results uploaded from FNAL or the x-ray test centers?

**Comment by khan62** [comment]
Batch Full Test Submit and Batch Consolidated Submit both now prompt for user name.

**Comment by jstupak** [comment]
This works, but we already know the shifters name when I construct the XML file.  If its not difficult for you, could I add the shifter name as a field in the XML file, then we take this info from there?  If its difficult, don't worry about it
