### ISSUE TITLE
Edit ROCs Function

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#161]
The edit ROCs page, while functional, is not user-friendly. Currently you have to select a module from a drop don list of every module, ordered by module ID (internal to SQL DB).

In my mind the best solution would be to order the drop down list alphabetically. However, if that's not easy to do, a useful half-step would be to change the URL for the page to use the module name instead of ID.

So instead of:
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/ROCedit.php?modules=330

change it to:
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/ROCedit.php?modules=M-H-1-44

This isn't top priority. It's just a quality of life improvement.

**Comment by gneeser** [comment]
It was low-hanging fruit, so I changed it to sort alphabetically.
