### ISSUE TITLE
Search by date

### ISSUE THREAD

**Issue by scarletnorberg** [puhep/pudb#162]
It would be very nice to be able to search for modules that are at Fermilab but that arrived at Fermilab in the last week.  Experts on call start there shift and we want to know what happened the week before and what is happening during our week on shift so being able to check the data base and say that a module arrived sometime in the last week would be great.

**Comment by jstupak** [comment]
based on discussion during the meeting, we would like to be able to search based on the date received and shipped

**Comment by gneeser** [comment]
All, 
I added filter options on the [Tested Modules List](http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php?) page to filter between dates for received and shipped fields. In the event that one end of the between statement is empty, it uses the start of production (2015-09-01) and the current date as the limits. 

-Greg
