### ISSUE TITLE
Change color of IV summary curves

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#163]
Hello,

I think it would be useful to change the color of the curves in all plots on http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/pos.php
such that modules with a Grade A in the IV measurement show up as green, those with a Grade B in the IV measurement show up as orange, and those that have a C show up as red.

Thanks,
Petra

**Comment by gneeser** [comment]
Petra,
How does this look? 
http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/pos.php?

-Greg

**Comment by merkelp** [comment]
Hi Greg,

that looks good.

Thanks,

Petra

**Comment by gneeser** [comment]
Petra,
The changes are live on the production version of the site. Let me know if you'd like any changes.

-Greg
