### ISSUE TITLE
Defects over time plots

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#164]
Not sure the plots "defects over time" on http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/fulltest.php are filled correctly. By now we should have a few modules showing up as failing the IV.
Is it maybe that if they fail something else, they get listed as that?

Thanks,
Petra

**Comment by gneeser** [comment]
I _finally_ was able to get enough time to get to the bottom of what was happening here. The graph now correctly includes the failing IV grades:
http://inky.physics.purdue.edu/cmsfpix//Submission_p/graphing/bad_modulegrapher.php

-Greg
