### ISSUE TITLE
missing configs?

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#165]
Hello,

I don't see any config files available on the test summary page for tested modules.  For example:

http://www.physics.purdue.edu/cmsfpix/Submission_p/download/configfiles.php?name=M-I-2-44

The zip file that was uploaded for this module can be found here:

https://www.dropbox.com/s/39hc1pbg0gog5tm/M-I-2-44.zip?dl=0

The xml file looks okay to me.  Any ideas?  Thanks

**Comment by gneeser** [comment]
It was a bug on my end, it should be working now. I successfully uploaded the zip for the M-I-2-44. Let me know if it gives you any more trouble.

**Comment by jstupak** [comment]
Thanks!

Do we have to upload tarballs again for all the tested modules?

**Comment by gneeser** [comment]
You won't have to do anything with the tarballs, but the zip files you will have to re-upload, I believe. At least for any modules where you need the config files on there.
