### ISSUE TITLE
is session timeout delay configurable?

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#166]
Hi,

Would it be possible to increase the amount of time after logging into the DB that it kicks you out?  Or was there some security concern that limited that parameter?

Thanks,

Jamie

**Comment by jstupak** [comment]
+1

**Comment by drberry85** [comment]
+2

**Comment by gneeser** [comment]
I'll look into making the time longer. I'll let you know what I find.

**Comment by gneeser** [comment]
All, 
I neglected to mention it recently, but a while back I did some digging into this and tried a couple of different things. After none of them worked, I checked with Purdue IT and it looks like any of my local changes are overriden by settings higher up the chain. 
For the time being, it seems 30 minutes is the best I can do. This can be extended indefinitely by loading or refreshing a page every 29 minutes, though I realize that is pretty far from ideal. When I have a little more downtime, I plan to revisit the issue.

-Greg

**Comment by drberry85** [comment]
This fills me with unbearable rage.

**Comment by NickHinton** [comment]
We're sorry Doug!

If the rage becomes too great, feel free to take it up with these guys:

[Science IT](https://www.science.purdue.edu/faculty-and-staff/scienceIT.html)

**Comment by merkelp** [comment]
Hi,
even if it's closed, may I suggest a compromise?
It would help greatly if there could be a login button in more locations 
than just the front page.
Especially on the tested modules page it would be very useful.
Ideally of course it should be on each module's page...

Thanks,
Petra

**Comment by jstupak** [comment]
and/or could every DB page automatically refresh every 29 minutes?

**Comment by drberry85** [comment]
What Petra said.
<img width="569" alt="buttonme" src="https://cloud.githubusercontent.com/assets/4803884/14756339/23f2bb44-08ae-11e6-87a2-d2d55f4e9c05.png">

**Comment by gneeser** [comment]
All,
The Log In is now a link that sends you to the login page. Just press the back button to return to where you were. 

Let me know if you have any trouble with it. There's a possibility it won't work in all browsers.

-Greg
