### ISSUE TITLE
Implementing X-Ray Grading

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#167]
Hey Greg,

I think we're ready-ish to implement the X-Ray grading. The grading should be as follows.
Fluorescence
Grade A: 40 < X-Ray slope < 60 
Grade B: 30 < X-Ray slope < 40 or 60 < X-Ray slope < 70
Grade C: X-Ray slope < 30 or X-Ray slope > 70

Double Column Efficiency
Grade A
Number of Double Columns below 95% efficiency = 0 and Number of Double Columns below 98% efficiency = 0

Grade B
Number of Double Columns below 95% efficiency = 1 or Number of Double Columns below 98% efficiency = 1

Grade C
Number of Double Columns below 95% efficiency > 1 or Number of Double Columns below 98% efficiency > 1

Double Column Uniformity (For Now)
Grade A: Lowest DC Uniformity > 0.80
Grade B: Lowest DC Uniformity > 0.50 and Lowest DC Uniformity < 0.80
Grade C: Lowest DC Uniformity < 0.50

Grade A: Highest DC Uniformity < 1.50
Grade B: Highest DC Uniformity > 1.50 and Highest DC Uniformity < 2.00
Grade C: Highest DC Uniformity > 2.00

We'll discuss this in the Monday meeting. I hope it's not too hard to implement.

Doug

**Comment by drberry85** [comment]
Hey Greg,

Here is the actual grading we want to use:
Double Column Efficiency
Grade A: Number of Double Columns below 95% efficiency = 0 and Number of Double Columns below 98% efficiency = 0
Grade B: Number of Double Columns below 95% efficiency = 1 or Number of Double Columns below 98% efficiency = 1
Grade C: Number of Double Columns below 95% efficiency > 1 or Number of Double Columns below 98% efficiency > 1

Double Column Uniformity (Requires DB and script changes)
Grade A: Number of Double Columns below 0.60 uniformity + Number of Double Columns above 1.50 uniformity = 0
Grade B: Number of Double Columns below 0.60 uniformity + Number of Double Columns above 1.50 uniformity = 1
Grade C: Number of Double Columns below 0.60 uniformity + Number of Double Columns above 1.50 uniformity > 1

The Double Column Efficiency we can implement now, but the Double Column Uniformity we can't do until two spots (Number of Double Columns below 0.60 uniformity and Number of Double Columns above 1.50 uniformity) are added to the database and our X-Ray scripts are modified. So for the Double Column Uniformity, we need you to add the spots to the database, then we can upload the values, and then you can implement the grading.

Doug

**Comment by gneeser** [comment]
Doug,
I've started working on implementing the changes. Do we still care about X-ray slope for grading? You didn't mention it in your second post, so I just wanted to make sure.

Also, do we want number of Double Columns below 0.60 uniformity / above 1.50 uniformity to be on a per-module basis, like the number of Double Columns below 95%/98% efficiency?

Further, how do you want me to handle null values for these fields? Should null values make a grade incomplete, or should they simply be ignored if null?

-Greg

**Comment by drberry85** [comment]
Greg,

I've started working on implementing the changes. Do we still care about
X-ray slope for grading? You didn't mention it in your second post, so I
just wanted to make sure.
No, we are not grading on x-ray slopes.

Also, do we want number of Double Columns below 0.60 uniformity / above
1.50 uniformity to be on a per-module basis, like the number of Double
Columns below 95%/98% efficiency?
Yes, we want both those values to be for the whole module.

Further, how do you want me to handle null values for these fields? Should
null values make a grade incomplete, or should they simply be ignored if
null?
If they are missing these values, the module should be graded as incomplete.

Doug

**Comment by gneeser** [comment]
All,
I added the capacity to submit and display the number of double columns below 0.60 and above 1.50 uniformity. The data can be viewed on the [Full Test Summary](http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-test-test) page, in that block of text near the top. To submit the data, add the tags to your xml in this format (inside the test tag):
<DC_BELOW_60_UNI>5</DC_BELOW_60_UNI> 
<DC_ABOVE_150_UNI>3</DC_ABOVE_150_UNI> 

Still working on adding the grading.
-Greg

**Comment by gneeser** [comment]
All,
The code to grade on the X-Ray criteria has been added in the test environment. I've tested it with a hand-made xml, but would you mind sending over a fully-formed xml with data when you have it ready?

Also, I plan to hold off on pushing the changes to the live version of the site, as that would change the grade of every module to "I" at the moment (with the exception of the hidden test module and rejected modules, which are automatically graded as "C").

-Greg

**Comment by drberry85** [comment]
Hey Daniel,

Once the modifications to the upload script is finished, could you send a
zip file to Greg to test it?

Thanks,
Doug

**Comment by drberry85** [comment]
Hi,

We updated our scripts to include that information and we already started
uploading the DC Unif values, like in M-G-1-40
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-G-1-40
It seems to be working. Do you still need the zip file?

On Mon, Apr 4, 2016 at 3:18 PM, Douglas Berry drberry@uic.edu wrote:

> Hey Daniel,
> 
> Once the modifications to the upload script is finished, could you send a
> zip file to Greg to test it?
> 
> Thanks,
> Doug
> 
> On Mon, Apr 4, 2016 at 3:13 PM, gneeser notifications@github.com wrote:
> 
> > All,
> > The code to grade on the X-Ray criteria has been added in the test
> > environment. I've tested it with a hand-made xml, but would you mind
> > sending over a fully-formed xml with data when you have it ready?
> > 
> > Also, I plan to hold off on pushing the changes to the live version of
> > the site, as that would change the grade of every module to "I" at the
> > moment (with the exception of the hidden test module and rejected modules,
> > which are automatically graded as "C").
> > 
> > -Greg
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/puhep/pudb/issues/167#issuecomment-205475485

## 

_Best Regards,_

---

_Daniel SandovalUniversity of Illinois at ChicagoPhysics Department *
*Office: SES 2156, Lab: SES 2259_
_Office   Phone: (+1) (312)-996-5648_
_email:  isando3@uic.edu isando3@uic.edu_
- ```
         isandova@cern.ch <isandova@cern.ch>*
  ```
- ```
         dansand@fnal.gov <dansand@fnal.gov>
  ```
  
  ---

**Comment by gneeser** [comment]
I agree it looks good. We should be fine without sending the zip file. 

Let me know when you have enough values submitted that you want the grading to be updated (which will be as simple as pushing the code to the live version of the site).

-Greg

**Comment by drberry85** [comment]
Hey Greg,

Based on Daniel's and Xuan's talk and feedback from Marco we're going to
loosen the X-Ray grading criteria. The double column efficiency grading
should be changed to:
Double Column Efficiency
Grade A: Number of Double Columns below 95% efficiency = 0 and Number of
Double Columns below 98% efficiency = 0 (unchanged)
Grade B: Number of Double Columns below 95% efficiency = 1 or Number of
Double Columns below 98% efficiency > 0
Grade C: Number of Double Columns below 95% efficiency > 1

The double column uniformity grading criteria do not need to be changed.
Again, don't enable the grading until we get feedback from Jack.

Doug

**Comment by NickHinton** [comment]
There are a large number of modules assembled at Nebraska and Xray tested at Kansas that don't have the new uniformity data in the DB. However they do have the efficiency data.  

Jack, can you link/send us the zip file for the data you uploaded for module M-L-1-23?

If we push the new grading criteria now there will be 50+ graded modules set to incomplete.

**Comment by gneeser** [comment]
All, 
Now that we've populated the aforementioned modules, I'm going to push the changes to the production version of the site. It's a fairly large change and brings with it several other changes/fixes I've made recently, so let me know if you see any bugs or problems.

-Greg

**Comment by gneeser** [comment]
The new grading scheme is now live. Let me know if you catch any problems.

-Greg
