### ISSUE TITLE
Busted IV Plot

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#168]
Hey Greg,
It looks like there is some issue in the IV plotting.
Doug
![bustedivplot](https://cloud.githubusercontent.com/assets/4803884/14082396/52ae340a-f4d5-11e5-9edf-4bc99401038b.png)

**Comment by jstupak** [comment]
did you try refreshing?  I saw a similar error the other day and just refreshing the page fixed it.

**Comment by gneeser** [comment]
Also, make sure you're not in Submission_t. I only mention that because I've been linking plots in Submission_t to showcase testing stuff, and I'm currently testing changes that would break that plot in Submission_t.

**Comment by drberry85** [comment]
John and Greg,

Yes, I did try refreshing and it didn't work. Greg, I'm not sure what you
mean by Submission_t. I am just using the 'IV by Position' button on the
http://www.physics.purdue.edu/cmsfpix/Submission_p/ page. The IV plot page
is http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/pos.php

Doug

**Comment by gneeser** [comment]
Submission_t is my testing environment; it's accessed by changing the url and some of the links I sent Petra used it. But that's not the issue, it seems. Module M-B-4-37 had an empty file uploaded that's causing the plots to crash. I'll remove the file soon; that should fix the issue.

**Comment by drberry85** [comment]
Works now, Thanks Greg!

**Comment by gneeser** [comment]
I removed the file and the plot is working again. I had to remove the IV scan on M-B-4-37 from 2016-03-25 to make it work, so that data has been lost.

**Comment by lantone** [comment]
yeah, i don't think the results for M-B-4-37 should have been uploaded.  good to know that duplicate results can potentially break things.
