### ISSUE TITLE
no moreweb results from today

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#169]
Hello,

I don't see any moreweb results from today's tests, some of which were uploaded ~5 hours ago.  Is there a problem, or Im just not patient enough?

Thanks!

**Comment by gneeser** [comment]
I'm taking a look now. It seems to have stalled for some reason. I'll let you know when it's back up.

-Greg

**Comment by gneeser** [comment]
It's churning away again. Let me know if the results don't appear or it seems to stall again.

-Greg
