### ISSUE TITLE
Need a report functionality to support module registration in P5 conditions database

### ISSUE THREAD

**Issue by lgspiegel** [puhep/pudb#17]
Periodically I would like to collect module information in a form similar to 

module  |  sensor  |       HDI        |     ROCs   0, ..., 15
-----------+-----------+-----------------+----------------------------
P-A-3-34        WL_FR_915    YHC69-1015-3-34    STSDRAT 25D, 35D, 03D, 36D, 15D, 18D, 21D, 34D, 27D, 32D, 04D, 14D, 29D, 30D, 13D, 26D
P-A-3-36        WL_TT_915    YHC69-1015-3-36    STSDRAT 16B, 03B, 12B, 18B, 24B, 21B, 14B, 22B, 04B, 11B, 05B, 07B, 06B, 15B, 17B, 13B
P-A-3-42        WL_LL_914    YHC69-1015-3-42    STSDRAT 75A, 74A, 52A, 47A, 55A, 58A, 53A, 65A, 62A, 49A, 64A, 67A, 56A, 54A, 63A, 76A
P-A-3-43        WL_CR_915    YHC69-1015-3-43    STSDRAT 43D, 44D, 45D, 47D, 46D, 42D, 41D, 39D, 16D, 05D, 17D, 07D, 12D, 48D, 40D, 38D

so that the report can be used as input to an xml generator.

**Comment by khan62** [comment]
We could generate the xml format directly, if you'd prefer. Just let us know what format and tags you want. If you just want the text output, we'll still need what information and delimiters you want.

**Comment by khan62** [comment]
On the detailed module list, there is now a link for "Module Report Document". Clicking it will download a .csv of the requisite information.
