### ISSUE TITLE
IV error

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#171]
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=M-K-3-20

**Comment by gneeser** [comment]
The most recent of the FNAL IV files was empty. Where in the chain that happened I'm not sure, but since this is the second time this has happened I'll have to look into it a little more.

**Comment by jstupak** [comment]
Do you want to look at the zip that was uploaded?

**Comment by gneeser** [comment]
That's a good idea, yeah. Thanks!

**Comment by jstupak** [comment]
https://www.dropbox.com/s/biclsksmwyw8div/M-K-3-20.zip?dl=1
