### ISSUE TITLE
missing config files

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#172]
Hello,

The config files for M-K-2-22 seem to have gotten lost in the upload.  The zip looks okay to me:

https://www.dropbox.com/s/xwrc9ek2t3yjthc/M-K-2-22.zip?dl=1

Is there a log you could check to see what happened?  It was lucky I noticed that this happened, so if it happens again it will probably go unnoticed.  Would be nice to fix the problem, if there is one.

Thanks

**Comment by gneeser** [comment]
I don't have a log I can look at (it only keeps one in the temp folder), but with the zip file I can do some debugging. I'll let you know what I find.

**Comment by gneeser** [comment]
Using the file you provided, I was unable to reproduce the error. If you look on the Config Files page, you'll see that it now has the configs:
http://www.physics.purdue.edu/cmsfpix/Submission_p/download/configfiles.php?name=M-K-2-22

All I did was re-upload with the file you linked to. Most curious. If you notice it happen again, please let me know right away. In the meantime, I'll see if I can add a check in the code to look for and flag such an occurrence.

**Comment by gneeser** [comment]
Along with the new X-Ray grading scheme, I pushed a change that should prevent this from happening again. If you see it anyway, please let me know.

-Greg
