### ISSUE TITLE
Search for Xray Eff and DC 

### ISSUE THREAD

**Issue by isando3** [puhep/pudb#173]
Hello, 

Could it be possible to filter modules by #DC with efficiency < 95 % and  98% and uniformity < 0.6 and > 1.5 ? 

Thanks

**Comment by drberry85** [comment]
Hey Greg,
I think this is a feature that both UIC and KU would really like to have. So please don't treat this as a low priority issue.
Doug

**Comment by gneeser** [comment]
Doug,
Sure thing. Now that the new grading scheme is about to be implemented, it moved near the top of my list. I'll keep you posted.

-Greg

**Comment by gneeser** [comment]
It's been added to the Tested Modules List. Let me know if you catch any bugs.

-Greg
