### ISSUE TITLE
Failure of batchallsubmit_proc.php

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#174]
Right now I can not upload, always getting this error message:
JpGraph Error: 25121: Empty input data array specified for plot. Must have at least one data point.

This happens for more than one module, so I don't think it's module specific.

Petra

**Comment by merkelp** [comment]
hmm, looking at the individual module's DB page, I see that the upload actually worked, the data are there. No idea what to make of that error message then.

**Comment by gneeser** [comment]
It's a problem I've been working on where sometimes we get an empty IV file. The short-term fix is to remove the empty IV files, and a long-term fix is coming soon.

**Comment by gneeser** [comment]
If you see this error again in the future, would you mind sending the file to me? I'm trying to collect as much data as I can to narrow down what's happening.

@merkelp @jstupak

**Comment by gneeser** [comment]
Along with the new grading scheme, I just pushed a fix that should prevent this from happening again. If you see it anyway, let me know.

-Greg
