### ISSUE TITLE
Database Down?

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#175]
Hey Nick and Greg,

It looks like the database is down. Is this a Purdue issue, or an issue with our database.
<img width="1280" alt="pudbdown" src="https://cloud.githubusercontent.com/assets/4803884/14717679/2d415ada-07b8-11e6-86fb-ec6b6d1eddf2.png">

Doug

**Comment by gneeser** [comment]
Doug, 
I'm getting normal behavior on my end. Could you check again? It could have been a short outage. 

-Greg

**Comment by drberry85** [comment]
Greg,
The problem has resolved itself for me, but Scarlet is still having an issue. I suspect it's her computer.
Doug
