### ISSUE TITLE
Fractional information

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#178]
Hello,

could we change this plot http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/testbybatch_grapher.php such that all bars are the same total size (=100%) and change the blue/red/yellow/green) parts to fractions of the total for that batch? I think it would be more informative when comparing batches with each other. They are always more or less the same size anyway, and when they are not we know it.

Thanks,
Petra

**Comment by drberry85** [comment]
Petra,

I would vote that we just have a second plot which has the percent yield
plotted as a function of batch and not the absolute numbers.

Doug

**Comment by gneeser** [comment]
Petra,
How does this look?

http://www.physics.purdue.edu/cmsfpix/Submission_t/graphing/testbybatch_fractional_grapher.php

Are there any changes you would like me to make? I can try experimenting with making adjustments for readability as well if you'd like.

-Greg

**Comment by merkelp** [comment]
Hi Greg,

looks great, thanks!

Petra

**Comment by gneeser** [comment]
My pleasure!

**Comment by drberry85** [comment]
Greg,

I'm being nit-picky, but could you change the plot maximum to 120 so the
legend doesn't coverup the data?

Doug
