### ISSUE TITLE
New ROC Failure Modes

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#179]
Hey Greg,

Could you add the following ROC failure modes:
Bad Trim no Bad DC
Iana Short
Idig Short
Low Iana/High Vana
Bad Bumps (Separate from partially detached ROC)
No Token Pass

Maybe add these later as they aren't well understood yet:
Pulse Height Issue
Noisy ROC

Let me know if there are comments or issues.
Doug

**Comment by gneeser** [comment]
Doug,
I added the new ROC failure modes. Let me know if/when you want me to add the two at the bottom.

-Greg

**Comment by drberry85** [comment]
Greg,

Add these two failure modes:
Unprogrammable
 Pulse Height Issue

Then I think we're done.

Doug

**Comment by NickHinton** [comment]
Unprogrammable and Pulse Height Issue have been added to the list of failure modes.

Doug, should I close this issue or leave it open for potential future additions?

**Comment by drberry85** [comment]
Greg,

I think you can close it. I'll reopen it if we need to add new ROC failure modes.

Doug
