### ISSUE TITLE
Addition of Mounted Module Count to Module Production over Time Plots

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#180]
(taken from a message from Petra)

Hi,

if I am not mistaken the 'Install' line is not starting to show up in
these plots:
http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/module_summary_grapher.php?plot_condition=log

Shouldn't the 22 modules that are on the first disk now show up there?

**Comment by NickHinton** [comment]
I believe the install line on that graph is the number of modules required to install FPix. We should add a running tally of modules mounted on blades.

**Comment by gneeser** [comment]
I added a "Mounted" line on the plot. Looks to me like it's displaying properly now.

-Greg
