### ISSUE TITLE
Next Testing Step Bug

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#181]
Hey Greg,

When I update the next testing step for M-M-3-03 or M-I-3-28 to rejected, it doesn't actually change the 'Next Testing Step' value in the DB.

Doug

**Comment by NickHinton** [comment]
It looks like Marco was able to reject M-M-3-03, and I was able to reject M-I-3-28 just now. I'm not sure what could have been causing your problem though. I'm going to close this issue, but if you encounter the problem again please let us know.
