### ISSUE TITLE
Add 'Mounted on Blade' modules on tested module list

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#182]
Hey Greg,

Could we add a 9th column to the "Tested Modules List" page, that has the modules which are on blade. Additionally, could you make them show up in the search as well. Currently when I search for "Mounted on Blade"==Yes, it returns 0 modules.

Thanks,
Doug

**Comment by gneeser** [comment]
Doug, 
I added the column for mounted on blade. The search didn't show anything because that column wasn't displayed, so I think we're good on that front. 

-Greg

**Comment by drberry85** [comment]
Do you know why the "Test Modules List" has 45 modules on blade when there is only 44 in the list?

**Comment by gneeser** [comment]
One of the DB test modules showing up where it shouldn't. I'll move it.

**Comment by gneeser** [comment]
I added an additional check to keep the test module from being counted in addition to it not being displayed.
