### ISSUE TITLE
updating M-Y-B-NY

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#183]
Hi,

I can't seem to affect a change in the "Next Testing Step" for this module:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=M-Y-B-NY

I'd like to set it to "Rejected".

Thanks,
Jamie

**Comment by gneeser** [comment]
Jamie, 
Modules require a comment to be rejected, in line with a request a while back. I'll add a disclaimer about that. 

-Greg

**Comment by lantone** [comment]
great, thanks!

**Comment by gneeser** [comment]
I added the disclaimer. If there are any other troubles with that, let me know.
