### ISSUE TITLE
unset ROC failure mode

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#186]
Hi,

I have this friend that accidentally set a ROC failure mode and wants to unset it, but it looks like at the moment there's no way to achieve that.  Do you know what he (or she) should do?

Thanks,
Anonymous

**Comment by gneeser** [comment]
I can either unset it through the mysql or add another option that resets the field to null. The first would be easier, but we have to figure this will come up again so I can make the feature if you want.

**Comment by lantone** [comment]
yeah, I think it'd be a very nice feature to have.  I'm now starting to spot other ones as I look through

**Comment by gneeser** [comment]
I added "Unset Failure Mode" as another option in the dropdown list. Selecting that option for a particular ROC will reset the failure mode to null. 

-Greg
