### ISSUE TITLE
test by batch page had sudden increase in ungraded modules

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#187]
Maybe you're already aware, but if not, the grades by batch histogram seems to have lost some of the grades:

http://inky.physics.purdue.edu/cmsfpix//Submission_p/graphing/testbybatch_grapher.php

**Comment by drberry85** [comment]
It looks like it's not flagging the rejected modules as grade C.

**Comment by gneeser** [comment]
It's probably a mistake I made when trying to optimize the graph load times. I'll look back and see where I went wrong.

**Comment by lantone** [comment]
good call doug - here's an example i found:

http://inky.physics.purdue.edu/cmsfpix//Submission_p/summary/summaryFull.php?name=M-L-2-41

it's rejected but still showing as Grade : I.  I bet it's all the modules that were manually rejected that are affected

**Comment by gneeser** [comment]
Ah, that tells me where it is in the code. I'll push out a fix over the weekend. Thanks the the sleuthing.

**Comment by gneeser** [comment]
The grading function is behaving properly again while maintaining the improved runtime. Let me know if you catch any bugs with this though.

-Greg
