### ISSUE TITLE
disagreement between modulereport2 and rest of DB

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#188]
Sorry to keep spamming you today, got another thing:
I just changed 2 ROC failure modes to "Unprogrammable" and it shows up here:

http://inky.physics.purdue.edu/cmsfpix//Submission_p/summary/test_list.php?param19=&param1=&param20=&param23=&param8=&param27=&param30=&param31=&param34=&param35=&param22=&comp2=%3D&param2=&param36=Unprogrammable&comp41=%3D&param41=&comp3=%3D&param3=&comp4=%3D&param4=&comp28=%3D&param28=&comp10=%3D&param10=&comp11=%3D&param11=&comp5=%3D&param5=&comp7=%3D&param7=&comp12=%3D&param12=&comp13=%3D&param13=&comp37=%3D&param37=&comp38=%3D&param38=&comp39=%3D&param39=&comp40=%3D&param40=&param9=&comp25=%3D&param25=&comp18=&param18=

but not in the corresponding lines here:

http://inky.physics.purdue.edu/cmsfpix//Submission_p/tmp/modulereport2.csv

Thanks,

Jamie

**Comment by lantone** [comment]
Hahaha, I refreshed the page seconds after creating the issue and the csv updated to include my changes.  Thanks for the lightning fast fix!

**Comment by gneeser** [comment]
Haha, anytime!
