### ISSUE TITLE
Modules Assembled from Wafer

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#19]
It would be nice to have a list of modules built out of a wafer visible from that wafer's summary page. That way we could see at a glance what fraction of modules have been bonded from a given wafer and which assembled modules they are.

**Comment by khan62** [comment]
On the wafer part summary pages, in the "Comprised of" section, if a sensor has been made into a module, that module's name will appear next to the sensor's name. Clicking it will bring you to the module's part summary page.
