### ISSUE TITLE
Additional ROC Failure Mode

### ISSUE THREAD

**Issue by LaurEnnesser** [puhep/pudb#190]
Hello,

We've noticed a number of modules have an issue where the pixels along the ROC edge are partially dead.

Could you add an option to ROC Failure Mode for "dead edge" in the database?

Thanks, 
Lauren E.

**Comment by lantone** [comment]
Hi @gneeser ,
How's your schedule looking?  If this is a quick thing to add, @laurenasaur  and I could start using it immediately.
Thanks,
Jamie

**Comment by gneeser** [comment]
Hey all,
I added the failure mode (it was a very quick thing to add).

-Greg
