### ISSUE TITLE
Consolidated batch submit page crashes but still uploads

### ISSUE THREAD

**Issue by apatel1995** [puhep/pudb#191]
When uploading to M-B-4-37 I saw that the page would reset on me and then I would have to reload. This only seems to happen with this one module. Despite the connection reset the file does get uploaded, which is not seen unless you view the module page.

![screenshot from 2016-07-11 09 46 06](https://cloud.githubusercontent.com/assets/9732214/16736112/476d36a8-4751-11e6-8ce4-7d24e6826d2f.png)

**Comment by gneeser** [comment]
Is it possible that you were having network issues at the time? Have you tried an upload on that module since then? Were the uploads closely spaced?

I ask because based on how the code is set up, I do expect that occasionally it will crash after most of the data is successfully uploaded, but the reset connection is not something I've seen before, nor is it an error I would expect, so I'm wondering if this is something unrelated to an actual bug in the code as opposed to a network issue.

**Comment by apatel1995** [comment]
I tried uploading on different days and on different machines. The same
thing happens. The data is completely uploaded then it waits for a server
response. The server probably never responds and then the browser just
outputs an error.

It only seems to happen to this module. There is a special study being done
on this module, so it is undergoing a lot of tests and all of the results
are uploaded after every one. Can it be due to the module having a too much
data on its page? If so then server is never able to respond before the
browser automatically times out.

**Comment by gneeser** [comment]
Yes, that would absolutely do it. My comment earlier was in error, I have seen this before. This has happened in the past and my predecessor specifically warned that the database was never designed to handle that amount of information on one module, and that if it was done again, this would happen. The experts at Fermilab were made aware of this at the time.

As we did last time this happened, we can delete test data, but without a major overhaul of how the database handles information there isn't a way around problems occurring from it. 

I seem to recall that other problems resulted from this amount of data, but I will have to check my records.

**Comment by drberry85** [comment]
Greg (and Jamie),

I think you can just clear out all the old plots for this module, or we can
tell the shifters to stop uploading results to lessweb for this guy. Jamie,
do you have thoughts?

Doug

**Comment by lantone** [comment]
Yeah, I agree, we can just remember to only upload to MoReWeb and not the database in the future.  And we can clear out any plots on the module page, they're all available via MoReWeb anyway.

**Comment by gneeser** [comment]
I'll clear out the plots tomorrow then. I'll let you know if I run into trouble.
