### ISSUE TITLE
add 'Deferred' to Next Testing Step

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#194]
Hey Greg,

We need to add 'Deferred' to the list of 'Next Testing Step's for the batch E modules. There should also be a deferred column in the test module list.

Let me know if you have issues or questions,
Doug

**Comment by gneeser** [comment]
Doug,
I added the Deferred step to the module edit page and the tested modules list. Let me know if you have any problems with it or catch any bugs.

-Greg

**Comment by drberry85** [comment]
Thanks Greg!

**Comment by gneeser** [comment]
My pleasure!
