### ISSUE TITLE
KU Xray Uploads are incomplete.  Not all data uploading.

### ISSUE THREAD

**Issue by jking79** [puhep/pudb#195]
Cecilia has brought it to our attention that the Moreweb information from KU's uploads is incomplete.  After a investigation I can see that we where uploading complete information but now are not.  This seems to be the case since the beginning of June.   After investigation is does not appear that our script has been changed since the end of May when it was written, at that time  we where getting full uploads.
## I included Cecilia's email and a copy of the tar file we are uploading for reference.

Hello,
now that MoreWeb is back, I am trying to grade the modules we have tested recently. Most of the MoreWeb X-ray results are incomplete, and it is not possible for us to make a determination by comparing the X-ray and BB results about the quality of the module. I thought that you had fixed the code. Is there a way this can be fixed going forward? Daniel and Doug can help if needed. It is pretty frustrating not being able to make a determination in these cases. You spent a lot of time testing these, and in some cases, we end up testing them again at UIC. This is really something we should be able to have sorted out by now.

These are the latest modules, for which the MoreWeb x-ray results are not complete:
M-P-2-20 
M-N-3-46 
M-G-1-44
M-G-2-13
M-P-5-17
M-K-2-02
M-P-5-37
M-P-4-46

M-O-3-30, the X-ray results are not in MoreWeb at all.

Thanks,
## Cecilia Gerber

[M-K-2-02_XrayQualification-17C-KU-160726-1538_2016-07-26_15h38m_0123456789 2.zip](https://github.com/puhep/pudb/files/384843/M-K-2-02_XrayQualification-17C-KU-160726-1538_2016-07-26_15h38m_0123456789.2.zip)

**Comment by gneeser** [comment]
Last I heard from the email chain, this issue seemed to have been resolved. Have you continued to have issues?

-Greg

**Comment by jking79** [comment]
Greg,

This Issue has been resolved.

Thank You

On Sep 13, 2016, at 2:32 PM, gneeser <notifications@github.com<mailto:notifications@github.com>> wrote:

Last I heard from the email chain, this issue seemed to have been resolved. Have you continued to have issues?

-Greg
