### ISSUE TITLE
Unmounting Blade from Disk

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#196]
Hey Greg,

We need a way in the database to remove a module from a blade. We have two modules that were damaged during installation and were removed from the blade. However, we cannot update the DB accordingly. Could you add an option in the DB so that a module can be remove from the blade?

Thanks,
Doug

**Comment by gneeser** [comment]
Doug,
There actually is a way to do this already, but it's not obvious. If you go to the module's full test summary page, then to manual update, you can set the Next Testing Step to Rejected, which will automatically change the assembly step to Rejected as well.

-Greg

**Comment by drberry85** [comment]
Thanks Greg,

I'll tell Petra, and we'll update the two modules accordingly.

Doug

**Comment by merkelp** [comment]
Thanks!

**Comment by gneeser** [comment]
Were you able to change their status successfully? I just want to double check before we close the issue.

**Comment by merkelp** [comment]
Hi Greg,

yes, it works.

Thanks,

Petra
