### ISSUE TITLE
Change IV sloper Grading

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#198]
Hey Greg,

Can you loosen the IV slope grade from 2 to 10 [I(V=150)/I(V=100) < 10]? Also, does this require any reprocessing, or will all the grade update automatically.

Doug

**Comment by gneeser** [comment]
At least on the database side, the grade is generated on the fly, so no reprocessing will be necessary and the changes will take effect immediately. I don't know about moreweb though. Does moreweb even grade on the IV?

**Comment by drberry85** [comment]
No, this is just for lessWeb. We can change it in MoReWeb, but that would
require us to reprocesses everything, which is a week long adventure at
this point.

Doug

**Comment by gneeser** [comment]
Doug,
I updated the IV slope criterion in the dev environment. It definitely seems to have made a difference, as you can see here:
http://inky.physics.purdue.edu/cmsfpix//Submission_t/summary/test_list.php?param19=&param1=&param20=&param23=&param8=&param27=&param30=&param31=&param34=&param35=&param43=&param22=&comp2=%3D&param2=C&param36=&param42=&comp41=%3D&param41=&comp3=%3D&param3=&comp4=%3D&param4=&comp28=%3D&param28=&comp10=%3D&param10=&comp11=%3D&param11=&comp5=%3D&param5=&comp7=%3D&param7=&comp12=%3D&param12=&comp13=%3D&param13=&comp37=%3D&param37=&comp38=%3D&param38=&comp39=%3D&param39=&comp40=%3D&param40=&param9=&comp25=%3D&param25=&comp18=&param18=

(Sorry for the wall of url, that's just how the page handles variables)

Looking at the remaining module that's mounted and still has a grade of C, M-P-3-13, it looks like it is still from the IV, but it just looks like a weird test result, probably not representative of the module. See here:
http://inky.physics.purdue.edu/cmsfpix//Submission_t/graphing/xmlgrapher.php?id=3381&scan=IV&level=module

For the 8 modules in Ready for Mounting that are still grade C, only one of them seems to be from the IV - module M-N-3-22, and that also seems like it's just a wonky test result:
http://inky.physics.purdue.edu/cmsfpix//Submission_t/graphing/xmlgrapher.php?id=4192&scan=IV&level=module

Based on this, it looks like the relaxed grading criterion works except in edge cases where the test results are just weird. I think that the slope criterion would probably have to be thrown out to grade those cases as anything but C.

Feel free to compare the results to the production environment. If you like what you see, I'll update some of the text to reflect the new criterion and push the changes through. 

-Greg

**Comment by drberry85** [comment]
Greg,

I looked at a few modules and it appears fine. The only module that I found
that still has a problem is M-Q-A-11. Do you know what the IV ratio is for
that module at -20C?

Doug

**Comment by gneeser** [comment]
I don't know the exact ratio, but looking at the module's IV here:
http://inky.physics.purdue.edu/cmsfpix////Submission_t/graphing/xmlgrapher.php?id=3993&scan=IV&level=module

I think that this is another strange result. I would estimate that the ratio is 5e-9/2e-10, or about 25.

**Comment by gneeser** [comment]
I have to say, it looks like there a large number of abnormalities at low voltage for the -20C results:
http://inky.physics.purdue.edu/cmsfpix///Submission_p/graphing/positiongrapher.php?level=fnal&scan=IV&loc=

(note that this is using the old criterion)

Is this an artifact of the low temperature test? I don't see it in the +17C tests, at least not as much:
http://inky.physics.purdue.edu/cmsfpix///Submission_p/graphing/positiongrapher.php?level=fnal_17c&scan=IV&loc=

**Comment by drberry85** [comment]
Greg,

Let's apply the change an see how big the effect is. We may still loosen it
further or disable it all together.

Doug

**Comment by gneeser** [comment]
I pushed the change through. Let me know if you catch any places that I missed.

**Comment by gneeser** [comment]
If there are no objections, I'm going to close this issue for now. If you want to make any more changes, feel free to reopen the issue and I'll get on it.
