### ISSUE TITLE
Cannot reset Run at -300V flag?

### ISSUE THREAD

**Issue by cegerber** [puhep/pudb#199]
Hello,
I tried to remove the check mark for "Run at -300V" for M-P-3-30 (twice), but it does not clear. Is there a trick I am missing? I even tried to enter a comment, but it did not make a difference.
Thanks,
Cecilia

**Comment by gneeser** [comment]
Cecilia,
It looks like I didn't correctly configure the code to clear the flag, and I implemented it so hastily I never tested that case. I'll have a fix pushed out by tomorrow.

-Greg

**Comment by gneeser** [comment]
Cecilia,
I pushed out the update and unset the run at HV flag for M-P-3-30. Let me know if you have any more trouble with it.

-Greg
