### ISSUE TITLE
Search fields

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#2]
On search page: (http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php)
- Explanation of search field (i.e. where it will search for your query)
- List of filters applied

**Comment by merkelp** [comment]
Comment by Kamal: 
Search function on this page is a direct copy of the search function on summary/list.php, which searches all parts in the database. Do we want a specialized search for the tested modules?

**Comment by khan62** [comment]
I took out the search field but added a "Name Includes" text box, which filters by the entered substring. This is a lot more intuitive than the old search function, as it doesn't redirect you to another page. Also, the parameters no longer reset after the filters are applied.
