### ISSUE TITLE
Warning message in HDI attached step

### ISSUE THREAD

**Issue by jsiado** [puhep/pudb#20]
Hi,
After the step of HDI attached to a sensor I am getting the following message.

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /net/copernicus/project1/cmsfpix/.www/Submission_p/assembly/bbm.php on line 29

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /net/copernicus/project1/cmsfpix/.www/Submission_p/functions/curfunctions.php on line 130

**Comment by khan62** [comment]
Can you tell me what page you're on and what module you're looking at?

**Comment by jsiado** [comment]
I was entering the data for the modules we received this week. It happens after I hit the submit button for three different modules. P-A-2-20, P-A-3-35, and P-A-2-35. Although the data was submitted.

**Comment by jsiado** [comment]
This is the page it sends me after hitting submit
http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/bbm.php?name=BL_RR_912

**Comment by khan62** [comment]
I found the issue. That step in the assembly changes the module's name. However, the code was still referencing the old name (which no longer exists) in the URL. I have changed the code; let me know if it still happens.

**Comment by khan62** [comment]
I'm going to close this; feel free to open it back up or start another Issue if you find anything new related to this topic.
