### ISSUE TITLE
new MoReWeb results not being processed

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#200]
Hi,

There is evidence to suggest results uploaded to MoReWeb in the last ~24 hours are not being processed.  Is there any way for you guys to confirm/deny that?

Thanks,

Jamie

**Comment by gneeser** [comment]
Jamie,
It looks like MoReWeb got stuck around 8:00 this morning. There wasn't anything in the log to indicate what happened, but I've restarted it. It found a bunch of new folders and is analyzing them now. I'll poke around tomorrow and see if I can find what happened.  

-Greg
