### ISSUE TITLE
more data stored per ROC?

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#21]
Now that we are storing x-ray results on a per module basis, is it possible to store additional info on a per module basis?  We would also like to store the number of bad bumps (both electrical and x-ray) and number of dead pixels this way, but its not essential.

**Comment by khan62** [comment]
Those three are now in the database and displayed on the Full Test Summary pages as per-ROC values. You can also upload the values on a per-ROC basis in a similar manner to how you can upload the xray_slope and xray_offset, using the same tags as before. I still need to make them filterable on Tested Module List and make a way to manually upload them. The per-module entry fields and XML tags are still there, but they aren't displayed anywhere and I'll probably remove them soon.

**Comment by khan62** [comment]
Tested Module List now filters by per-ROC values for bad bumps and dead pixels in the same way it filters by xray slope and offset: the module is shown if at least one ROC meets the criteria

**Comment by jstupak** [comment]
I just uploaded the following zip:

http://home.fnal.gov/~jstupak/files/P-A-3-41.zip

However, I don't see the tables filled with the number of bad electrical bumps or dead pixels.  I have a couple other problems with this zip as well, but I will open separate issues to make the bookeeping easier.

**Comment by khan62** [comment]
Looking at master.xml, it seems that you have <ROCS> nested inside <TEST>, but the parser checks for those tags separately. However, I think I prefer this layout, because otherwise the <TEST> tag is pretty empty, and it eliminates the need to have two <NAME> fields. I'll update the parser and let you know when that's done.

**Comment by khan62** [comment]
The parser is updated, and I submitted the electrical bump and dead pixel data for P-A-3-41. The example master.xml has also been updated.
