### ISSUE TITLE
dead electrical bumps missing

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#22]
Hello, I just uploaded a zip file with some new x-ray data.  The xml file contains:

<?xml version="1.0" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ROCS>
    <NAME>P-A-3-42</NAME>
    <ROC>
      <POSITION>0</POSITION>
      <XRAY_OFFSET>0.0</XRAY_OFFSET>
      <XRAY_SLOPE>0.0</XRAY_SLOPE>
      <DEAD_BUMPS_XRAY>0</DEAD_BUMPS_XRAY>
    </ROC>
...

The results of the upload are here:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-3-42

I see the slope and offset fields are filled, but not the dead bumps.  Did I use the wrong field name?

**Comment by jstupak** [comment]
github garbled the xml again

```
<?xml version="1.0" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ROCS>
    <NAME>P-A-3-42</NAME>
    <ROC>
      <POSITION>0</POSITION>
      <XRAY_OFFSET>0.0</XRAY_OFFSET>
      <XRAY_SLOPE>0.0</XRAY_SLOPE>
      <DEAD_BUMPS_XRAY>0</DEAD_BUMPS_XRAY>
    </ROC>
```

**Comment by khan62** [comment]
The tag name is BADBUMPS_XRAY. The electrical test one is BADBUMPS_ELEC. Also, the dead pixels one is DEAD_PIX. Other than that it looks good.

**Comment by jstupak** [comment]
thanks!
