### ISSUE TITLE
FNAL IV curve missing from module summary page

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#23]
The IV curve from FNAL is not showing up on the plot with the "on wafer" and "assembled module" IV scans anymore.  Same zip as my other issues:

http://home.fnal.gov/~jstupak/files/P-A-3-41.zip

**Comment by khan62** [comment]
The problem has been resolved. You can see the new graph at 
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=P-A-3-41
