### ISSUE TITLE
problem with a specific zip file / unable to load any results to DB

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#26]
Mo and I tried to upload this zip file twice, but there seems to be a problem:

http://home.fnal.gov/~jstupak/files/P-A-3-22.zip

The module does not appear in the tested module list.  It does appear as a recently tested module, but our IV scan and other info is not shown, nor is the module graded.  Is there something wrong with the zip file?  Thanks

**Comment by chenxvan** [comment]
I had the same problem for module P-A-2-20 and P-A-3-35. Here are the zip files for these two modules:
https://www.dropbox.com/sh/2jj15j7xbuqivab/AADUT_otdQMqte6mL0Jfmuj0a?dl=0

**Comment by khan62** [comment]
I see P-A-2-20 and P-A-3-35 on the tested module list. P-A-3-22 isn't there because it doesn't have any  associated ROCs. I will look into why the data isn't being uploaded properly.

**Comment by jstupak** [comment]
Yes, we see them (2-20 and 3-35) too.  But none of the information we uploaded is there.

Naively, it seems like uploading data for 3-22 caused some error and the DB has not recovered, so we can't upload new data.

**Comment by khan62** [comment]
I was unable to recreate the bug with P-A-2-20. Can you try uploading P-A-3-35 again and checking if it happens again?

**Comment by khan62** [comment]
I noticed with P-A-2-20 that, though some of the zipfile was uploaded, some of the pictures, all of the config files, and the IV scan were not uploaded, as the page timed out. I want to stress that uploading these pictures and config files through MoReWeb would alleviate this problem.

**Comment by jstupak** [comment]
I just tried again with another module and I can't upload anything

**Comment by khan62** [comment]
Try again; you may have caught me in the middle of making changes to the database. I just tried P-A-3-35 and it worked without any problems.

**Comment by jstupak** [comment]
Looks good to me.  Also, it seems all our plots now make it into the DB :)
