### ISSUE TITLE
feedback upon upload

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#28]
Is it possible to add some feedback after someone uploads a zip file to the DB?  A simple message in the case of success would be nice, and a more detailed error message in the event of failure.

**Comment by khan62** [comment]
I added a few return messages. The page will now inform you if:
- The code executed successfully
- Not all forms were filled
- master.xml could not be read
- The zip file did not finish parsing

Are there any more you'd find helpful?

**Comment by jstupak** [comment]
I think this is good, thanks!
