### ISSUE TITLE
grade looks wrong

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#29]
By my math, this module should be a B, but it is graded as an A.  I count 1.8% bad bumps

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-3-02

**Comment by khan62** [comment]
Thanks for the heads up. There was a bug that was overwriting a "C" grade if another ROC had an "A" grade. It is now fixed.

Also, for which ROC are you getting 1.8%? P-A-3-02 is graded as "C" because of the 1000+ bad bumps/dead pixels on ROC 2

**Comment by jstupak** [comment]
I did my math based on the sum of all ROCs, but I guess you are saying it is based on the worst ROC?

**Comment by khan62** [comment]
Petra's email said that the grading should be done per-ROC, and the grade of the worst ROC should be the grade of the module

**Comment by jstupak** [comment]
okay, Petra is the boss :)
