### ISSUE TITLE
Recently Updated Page

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#3]
I think it would be useful to have a page that lists the (5, 10, 20?) most recently updated modules along with links to their summary pages, who submitted the update, and what the update was.

**Comment by khan62** [comment]
I have made a page of recently updated modules: 
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/recently_updated.php

It lists the 10 most recently updated modules. It will not take into account updates to constituent parts (sensors, HDIs, etc), nor will it consider adding an IV/CV scan as an update. 

I still have to include the features of who updated the parts and what the update was.

Do we want similar lists for other parts? Do we want this list to be longer/shorter? Do we want other features on this page?

**Comment by NickHinton** [comment]
I don't think we need a similar list for any other parts.

I'd like the list to include who did the update and what the update was (both mentioned above), but also any comments associated with the update and the location of the part.

**Comment by khan62** [comment]
The Recently Updated page will now display user, update, and associated comments for new updates. Currently this only works if the update is an Assembly Status update, but I'm in the process of adding more.

**Comment by khan62** [comment]
It now tracks detailed information for a number of forms. However, in places where the user isn't asked for their name, it just says "User".
