### ISSUE TITLE
missing FNAL IV curve

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#30]
our IV curve is missing:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=P-A-3-02

**Comment by khan62** [comment]
I'm not sure what you mean. Looking at the page, I can see the "Module at FNAL" curve on the IV plot.

http://www.physics.purdue.edu/cmsfpix/Submission_p/pics/graphs/module_313_IV.png

**Comment by jstupak** [comment]
It just showed up then.  Should there be some delay?

**Comment by khan62** [comment]
It's possible. The filesystem the graph is on is handled by Purdue's IT department. Sometimes it takes a few minutes for changes to the code to propagate to the webserver, so it's possible the same process is at work here.
