### ISSUE TITLE
DB Down

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#32]
I can't access the DB

**Comment by NickHinton** [comment]
The physics building IT network is down. They are working on fixing it now, but the DB will be unavailable until the network is restored.

**Comment by jstupak** [comment]
thanks for the info.  Is there any estimate on when it will be back?

**Comment by NickHinton** [comment]
None yet. They are working on it now though.

**Comment by NickHinton** [comment]
The IT group has told me that the database will be unavailable until Wednesday morning.

**Comment by NickHinton** [comment]
The database is up now. The IT group was able to deploy a fix early.
