### ISSUE TITLE
notes on full test summary page

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#33]
Can we add the ability to put notes on the full test summary pages, like we have on the part summary page?  They should probably show up above all the plots, but below the other information.  Thanks

**Comment by khan62** [comment]
Do you want this to be a separate set of information from the part summary notes? Or do you want a copy of those notes?

**Comment by jstupak** [comment]
Separate. This would be info related to testing at fnal, not assembly

**Comment by khan62** [comment]
There is now a notes field for the full test summary page. Currently, you can add notes through the "Manual Update" button; I am in the process of adding the ability to add notes through xml.

**Comment by khan62** [comment]
Notes can now be uploaded via xml as well, using the tag <NOTES> under <TEST>. The example xml file has been updated to reflect this.
