### ISSUE TITLE
FNAL IV curve issue

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#34]
The first time I view the part summary page after uploading results, the FNAL IV curve sometimes doesn't show up.  I know its minor, but someone is bound to complain

**Comment by khan62** [comment]
Does it not happen every time, only sometimes? If so, it might have to do with a disconnect between when the graph's picture file is updated vs when the webserver recognizes the change.

**Comment by jstupak** [comment]
I have only noticed a few times, so Im not sure.  I will keep an eye on this in the future

**Comment by khan62** [comment]
The graphs used to load dynamically, but I changed it because it took too long on certain pages (Detailed Module List, specifically). I can change it back for the part summary pages, so it will always pull fresh data from the database rather than displaying a static image.

**Comment by khan62** [comment]
The graphs now load dynamically on the part summary pages.
