### ISSUE TITLE
module sorting issue

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#35]
If I click on "shipped" on the "assembly status" page, I get a list of modules which uses the old names

**Comment by jstupak** [comment]
ooops, looks like the new module names are used for newer modules.  But the way modules are sorted is  strange.  If I click "last modified" or "assembly date" I get the new modules at the top.  But if I click "ship date" I get new modules at the bottom

**Comment by khan62** [comment]
How do you want each of them to be sorted? For all of the dates, do you want newest at the top? Then the other ones alphabetical?

**Comment by jstupak** [comment]
yes, please.  that would be perfect

**Comment by khan62** [comment]
Done.
