### ISSUE TITLE
location

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#36]
IIUC the location is updated to FNAL as soon as a module is shipped to FNAL.  I think it would be better to mark these modules as "in transit" and force us at FNAL to update the location upon receipt.

**Comment by frmeier** [comment]
+1
Would make something like "In transit to X" where X is the destination.

**Comment by khan62** [comment]
Promoting a module to "shipped" now sets the location as "In transit to X". When it's received, use the "Update Location" link on the module's Part Summary page to change the location to X.
