### ISSUE TITLE
"to be tested" list

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#39]
Can we create a list of modules which need to be tested?  Basically, when a fully assembled module arrives at FNAL it should be added to the list, and when it receives a grade it should be removed.  thanks!

**Comment by khan62** [comment]
This functionality already exists. If you go to the Tested Module List, if you filter by Grade = I and Current Location = Fermilab, it will give you this list.

**Comment by jstupak** [comment]
Cool! thanks
