### ISSUE TITLE
missing Fermilab in new location

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#4]
I just tried to change the location to Fermilab for this part:
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/updatelocation.php?name=M_CR_901
but it is not available.

**Comment by merkelp** [comment]
and the same for this module:
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/updatelocation.php?name=M_CL_919

**Comment by NickHinton** [comment]
It looks like Fermilab is not an option for the change location function on any of the shipped parts. However, when I tried to do a test change on M_CL_919 to CERN, it changed the location to Fermilab even though Fermi was not an option.

P.S. Kamal is on vacation this week, so this issue may not be resolved until next week.

**Comment by khan62** [comment]
The locations have been fixed. I tested it with M_CL_919; I moved it to CERN and back to Fermilab.
