### ISSUE TITLE
data not entered properly

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#40]
Although data has been uploaded for this module, the number of dead bumps etc is not populated at the top of the page, and consequently no grade assigned:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-3-22

**Comment by jstupak** [comment]
Ditto:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-2-22
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-2-37

**Comment by khan62** [comment]
I can see that P-A-3-22 didn't receive those values is because it doesn't have any ROCs. I am not sure about the other two. Try uploading a zip of just the test data, with no pictures. It could be that the page timed out before it got to the data.

**Comment by jstupak** [comment]
I took all the plots out of the xml file and re-uploaded.  It looks like it worked since the module shows up in the recently updated list, but the ROC fields are still empty.

**Comment by khan62** [comment]
I see you tried with 3-22. That one will still not work because it doesn't have ROCs associated to it. You'll have to use the ROC Submit page to populate the module with ROCs before it can accept the test data.

**Comment by jstupak** [comment]
This module is not listed on that page

**Comment by jstupak** [comment]
Any idea why there are no ROCs attached to this module?

**Comment by khan62** [comment]
That is very strange. I will look into it.

**Comment by khan62** [comment]
3-22 now has ROCs, though currently all of the ROC names are empty strings. They can be changed here:
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/ROCedit.php?modules=155

3-22 should now be capable of holding test data. If it still doesn't work, there's another underlying problem.

**Comment by jstupak** [comment]
3-22 now has the info filled.  thanks

But this raises the question of why these ROCs were not filled in the first place.  Could it be human error on the part of someone at Nebraska, or do you think its a bug?

And I tried again with 2-22 with no pictures, but the data is still not filled.  You can see the zip file here:

http://home.fnal.gov/~jstupak/files/P-A-2-22.zip

**Comment by jstupak** [comment]
ahhhh, I think 2-22 is my fault.  These are old zip files from before the format changed

**Comment by khan62** [comment]
I see that you've added data for 2-22 and 2-37, so I'm going to close the issue.
