### ISSUE TITLE
clear module test data

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#41]
Is there a way for regular users to clear the test data for a given module?  It may happen that data is uploaded and then a problem is found (it has already ahppened).  It would be nice to remove the junk info in this case

**Comment by khan62** [comment]
Is it a problem that can't be fixed by overwriting with correct data? If so, I can do it manually. I wanted to avoid delete functions as much as possible; the website doesn't even have delete permissions on the MySQL database.

**Comment by jstupak** [comment]
the plots (unfortunately in this case) don't get overwritten.  I understand the hesitancy to allow people to delete data.  One solution would be to let plots with the same name overwrite old plots, but I don't love this solution.  Lets leave everything as is for now.  Thanks
