### ISSUE TITLE
consolidated batch submit test file

### ISSUE THREAD

**Issue by malhusse** [puhep/pudb#42]
Hello Kamal

I wanted to test the database and tried uploading a "test" text file.
The database accepts it and says file uploaded successfully. I'm not sure what it did with it though.

I would like to test automating the consolidated batch submit process, what kind of file should i test with

**Comment by khan62** [comment]
There's a specific format that the database expects for the consolidated batch submit. The success message on uploading an incorrect file is a bug that I'll need to fix (Thank you for finding it!). I should also make instructions more clear on how to properly format a submission.

**Comment by khan62** [comment]
I added instructions on the Consolidated Batch Submit page. Let me know if anything needs to be expounded on.

**Comment by malhusse** [comment]
Since the database checks if the file is .zip now, i will close this.
