### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#43]
Hello,

could you please increase significantly the font size on all the axis labels, plot labels, titles, etc. of the various summary plots? It is impossible to read anything.

Thanks,
Petra

**Comment by khan62** [comment]
I increased all of the fonts to their maximum on this graph:
http://www.physics.purdue.edu/cmsfpix/Submission_p/graphing/test_modulegrapher.php

If that looks ok I can do the same with the other graphs.

**Comment by merkelp** [comment]
Hi,
I still find it pretty small, but if it's the largest available I guess we have no other choice.

Thanks,
Petra

**Comment by khan62** [comment]
I also made the colors more distinct on the graphs. By default there were two very similar green colors that were confusing, so I changed them. Let me know if you want a different palette.
