### ISSUE TITLE
Can't upload test results to DB

### ISSUE THREAD

**Issue by chenxvan** [puhep/pudb#44]
![screenshot from 2015-07-30 13 44 23](https://cloud.githubusercontent.com/assets/7559253/8992025/da39d4d8-36c1-11e5-9634-6faea2c6d28e.png)
Hi,

I tried to upload the test results to the DB. i have been told that the file i uploaded was not a .zip file, which is not true. Do you know what's happened?
Thanks,

Xuan

**Comment by khan62** [comment]
I apologize; that was a syntactical error on my part. The page should now be functional.
