### ISSUE TITLE
virtual module missed

### ISSUE THREAD

**Issue by jmonroym** [puhep/pudb#47]
Yesterday I was updating the database as part of the stress test and I faced two issues.

I used to update the data base going through the assembly status>ready for HDI assembly way, where I can find the module I want to update, so next, I choose the HDI attached to that module (BL_CL_951), however, there is not any indication of the HDI location over there and I used one virtual HDI "located" at Purdue (the 1815-1015-50-19). The thing is that now I cant find my module and the HDI appears as attached to another module (not mine) by Alex. Now we have at Nebraska one extra HDI and one missed module. I guess the status of my module needs to be reset. It would be great if you can include a flag(or filter) which indicate the location of the HDI's when the user follows the way I used to update the data base.

**Comment by khan62** [comment]
This seems like an interesting bug. I found the new module here:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=M_CL_951
It says "HDI Attached", but there isn't one, so the HDI-based name is strange. I will try to figure out what happened.

**Comment by khan62** [comment]
To thicken the plot, it seems that your module was promoted to "HDI Attached" before the other one was, which means when you promoted your module it didn't recognize that you had selected an HDI. I'm not sure how this happened, but I've reset the module back to "Ready for HDI Assembly". Hopefully it doesn't happen again or, if it does, we have a better idea of what happened.
