### ISSUE TITLE
attach a file/report when updating the data base 

### ISSUE THREAD

**Issue by jmonroym** [puhep/pudb#48]
Here at Nebraska, after each step in the production chain is done, the operator create a report with details and comments from the process. When updating the data base there is an optional comment box where to write, however I would like to have the option to upload the report I have created instead of rewrite my comments. is that possible?

**Comment by khan62** [comment]
There is now an optional "Comments File" input on the assembly pages which takes a text file and appends it on a new line after the written comments for each step. Currently this function is only on the module assembly page, but if it is something that is wanted elsewhere I can propagate it to other pages.

Feel free to test this out and let me know if anything doesn't work or should be changed.

**Comment by jmonroym** [comment]
Does it takes only text files or can I upload pdf/word files? Our reports are in word/pdf format. Can this feature be extended to accept word/pdf files?

**Comment by khan62** [comment]
I know right now the database does not have the functionality to read word or pdf documents. I can look into it, but no guarantees

**Comment by NickHinton** [comment]
The comment file uploaded for P-B-5-34 is unreadable. Is this an issue with the file or the DB upload function?

**Comment by jmonroym** [comment]
it is a word (.doc) file, so I guess the functionality to read word or pdf documents is still not ready.

**Comment by NickHinton** [comment]
My understanding is that uploading .txt files will work, but .doc files might not be possible. Can you convert your notes into .txt format before uploading them?

**Comment by khan62** [comment]
The functionality to read word and pdf documents is something that would need to be handled on the ITaP side, which is not something we can rely on as a timely solution. I will add a check to make sure only .txt files are uploaded, so this doesn't happen again.

**Comment by jmonroym** [comment]
As I mentioned before, our reports are automatically generated by labVIEW using a template where the information is formatted. We certainly can convert the document, but the format  will disappear and the information  will be messed up. So I guess we will have to retype the comments on the DB page.

**Comment by khan62** [comment]
The form now filters out any file that is not a .txt
