### ISSUE TITLE
missing current location field

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#54]
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=P-A-2-35
is missing the current location field

**Comment by merkelp** [comment]
this one as well:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=P-A-2-33

**Comment by khan62** [comment]
The "Current Location" field doesn't show up until a part is promoted to Shipped.
