### ISSUE TITLE
upload problem

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#62]
I have tried uploading several very simple zip files to the DB today.  In each case, I get the message that the data was uploaded successfully.  However, the module does not appear as recently updated, nor does the new information appear on the module test result page.

A few example zip files I tried can be found here:
http://home.fnal.gov/~jstupak/files/P-A-3-02_1.zip
http://home.fnal.gov/~jstupak/files/P-A-3-02_2.zip
http://home.fnal.gov/~jstupak/files/P-A-3-02_3.zip

**Comment by khan62** [comment]
After being puzzled by this for quite some time, it seems like the zip files simply aren't being unzipped. I have no idea why this is the case, but I wanted to give a progress update.

**Comment by khan62** [comment]
I was able to upload your example files, so I believe the issue is now resolved. This is probably the most bizzare problem I've had with the database thus far, so let me know if it starts acting up again.
