### ISSUE TITLE
Change URL for Batch Module Submit

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#63]
Our batch module submit page currently points to http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/batchrocsubmit.php. I've changed the title of the page to 'Batch Module Submit', but I assume you need to change the php file name from batchrocsubmit.php to batchmodulesubmit.php. I'm not familiar enough with the database to trust myself to do that, so I leave it up to you.

**Comment by khan62** [comment]
The only references to the file were in the main menu, batchrocsubmit, and batchrocsubmit_proc so I just had to change the names of the files and the references there.
