### ISSUE TITLE
BL_LL_905 Bare Module Leakage Current Pass/Fail is Wrong

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#65]
This module breaks down at -110V, and all the measured currents and voltages are negative. So it should fail both the slope and 150V checks, but it is listed as passing on the DB.

**Comment by khan62** [comment]
There isn't any data after 110V, so it's probably considering I(V=150) = 0, which would make it pass both. I'll need to make it consider nonexistent values a different value; I think PHP has a constant for infinity that could be used here.

**Comment by khan62** [comment]
It is now set so that if the value is not found for either 100V or 150V, for criteria purposes it is effectively set to infinity. This may be a problem if there isn't a value for 100V, as this would cause I(V=150)/I(V=100)<2 to always pass.

**Comment by merkelp** [comment]
I would think during production we don't want a grade for a module which does not have a proper iv measurement. It would be safer to set the grade to d or such as a warning.

Petra
