### ISSUE TITLE
New HDI Upload Excel File Test and TBM Wafer Info

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#67]
We've gotten a second HDI batch excel file (sent over email). It includes a field for TBM wafer number and module carrier number. Can we make sure this format is compatible with the HDI batch upload command?

Can we also include the TBM wafer number in the HDI table? It would also be nice to display it on the module page as well.

**Comment by khan62** [comment]
It doesn't look like the new excel file would affect the current process, and it would be relatively easy to add the new fields. Are the TBM wafer number and module carrier number going to be in every HDI excel file from now on?

**Comment by NickHinton** [comment]
I believe the TBM wafer ID will be in every Excel file, but module carrier # might not be.

**Comment by gneeser** [comment]
Added TBM wafer fields in the DB and added code to display on the HDI page. Note that for HDI that were not submitted with the wafer info, "No Data" will be displayed.
