### ISSUE TITLE
clicking on images gives blank page

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#69]
I am clicking on images here:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-2-23

All I get is a blank page.

**Comment by NickHinton** [comment]
I can't reproduce the error. I was able to view all of the half dozen images I clicked on.

Is the web page loading the images in a new tab that has nothing there? Could you post a screenshot that includes the URL?

**Comment by jstupak** [comment]
Must have been a momentary glitch.  It is working for me now.

But for the record, yes I got a new window with nothing in it.  Screen grab attached
<img width="1440" alt="grab" src="https://cloud.githubusercontent.com/assets/4885475/9862191/88b1c4d2-5b37-11e5-89a0-7ce1ae07b3b4.png">
