### ISSUE TITLE
summaryFull.php page with MoreWeb results

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#7]
Hi, when clicking on a summaryFull.php page of a module that has the MoreWeb results uploaded, the buttons like "Back to Part Summary" are buried way at the bottom. It would be better to have these buttons near the top of the page, before the MoreWeb results.

One example module is P-A-3-42.

Thanks,
Petra

**Comment by khan62** [comment]
I have updated the page so that the buttons now "float" above the page and are at the same position on the screen regardless of scrolling. Does this work?

**Comment by khan62** [comment]
John pointed out that some of the Full Test Summary pages have picture arrays that end up under the floating buttons, so I moved the buttons to the top of the page
