### ISSUE TITLE
Adding Sintef Wafer Measurement Data to DB

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#71]
We need a way to upload Sintef's IV data to the DB for all the production wafers. We will be uploading the data in large batches, with measurements for each wafer as tabs within a large Excel file.

It would be even nicer if this function could also populate the DB with these wafers before adding the measurement data. That would automate the majority of the wafer handling. Always a plus. 

We want to upload the data for all the wafers contained within the Excel file. There will be some sensors that break down early, but we want that data in the DB too.

There will need to be a conversion from the Sintef naming convention to ours. I think such a conversion would be B2 = 102, B25 = 125, C2 = 202, C25 = 225, D2 = 302, etc...but I need to make sure of this.

**Comment by khan62** [comment]
Just a few questions:

Can we always assume that, if this form is being entered, the wafers don't already exist in the database?

Can you confirm that the conversions between numbering schemes is correct?

What do we want the "run begin timestamp", location, and "initiated by user" to be?

**Comment by NickHinton** [comment]
1) I think that's likely to be the case, yes. However, can you add a conditional statement like: "If this wafer exists, do nothing,"?
2) I can confirm that the numbering scheme is:
Bxx = 0xx
Cxx = 1xx
Dxx = 2xx
3) I'm not sure what the "run begin timestamp" is. The location of testing and handling of the wafers is Fermilab. Is that what the location field is referring to? "Initiated by user" can be Nick.

**Comment by khan62** [comment]
The "run begin timestamp" is the timestamp for when the IV scan was initiated. I can leave that blank, if we don't want to use the time at which it was uploaded. I don't think we're gonna get the accurate information from Sintef.

Location is where the IV test was run. Should I put down Sintef?

I can also have a user-input field on the webpage that can map to "initiated by user"

**Comment by khan62** [comment]
Would you be able to send me the wafer document in the xml format so I can test the page? I'm not using Microsoft Office and the program hangs up when I try to do the conversion myself.

**Comment by NickHinton** [comment]
I think we can leave the run begin timestamp blank in that case.

Go ahead and put Sintef for the location. 

The user-input field sounds good.

I'll send you the two files I have for the first two batches.

**Comment by khan62** [comment]
The "Batch Wafer Submit" page is now live, and I have uploaded the wafers and the on-wafer IV scans for the first batch (001 through 045).
