### ISSUE TITLE
Upload file for Module

### ISSUE THREAD

**Issue by drberry85** [puhep/pudb#72]
Hey Kamal,

Could you add the ability to upload general files about a module. On the part summary page, could we add a button that says, "Upload File". The uploaded file doesn't need to be parsed by the database. Just store it on the server and allow other users to download it later.

Doug

**Comment by khan62** [comment]
I've repurposed the "Config Files" page as "Extra Files". It's functionally the same, I just wanted to open up the page to be available to any files you may want to upload. I've also added a button to access the page on the Part Summary page.

**Comment by NickHinton** [comment]
Where do we go to add files to the 'extra files' page?

**Comment by khan62** [comment]
It looks like at this point it has to be done through consolidated batch upload. Do we want a designated page?

**Comment by NickHinton** [comment]
Yes, I think that would be useful.

**Comment by khan62** [comment]
There is now a page accessible from the "Add Extra File to this Part" button on the module part summary page where extra files can be uploaded
