### ISSUE TITLE
picture timestamps

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#74]
It seems that the timestamp uploaded with test results is being ignored.  I uploaded the following xml file:

http://home.fnal.gov/~jstupak/files/master.xml

You can see the results at the bottom of the module test results page have today's timestamp, not the timestamp provided in the XML file:

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-2-04

**Comment by khan62** [comment]
The user-submitted time functionality is now re-enabled.
