### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by jstupak** [puhep/pudb#77]
I just got this error message trying to upload test results:

An error has occurred and the comment has not been addedJpGraph Error: 25121 Empty input data array specified for plot. Must have at least one data point.

What does this mean?

I tried to upload data for module P-A-3-28.  But I now see this module is referred to as M_TT_922 in the DB.  Could this be the problem?

The data I uploaded can be found here:

home.fnal.gov/~jstupak/files/P-A-3-28

**Comment by gneeser** [comment]
I changed the name to P-A-3-28; we should confirm that this fixes the problem just to make sure our suspicions were correct.

**Comment by jstupak** [comment]
yup, that fixed it.  Thanks!
