### ISSUE TITLE
Flip chip bonder

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#78]
Hello, can we please make the flip chip bonder a searchable field?

Thanks,
Petra

**Comment by NickHinton** [comment]
Where would you like to search for this? I'd assume on the tested module list:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/test_list.php
Is that correct?

Thanks,
Nick

**Comment by merkelp** [comment]
Hi Nick, yes that would be fine.

Thanks,
Petra

**Comment by gneeser** [comment]
Modules are now searchable by flip chip bonder.
