### ISSUE TITLE
old module name in URL

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#8]
Hi,
the URL of the part summary page (bbm.php) and the page one reaches from test_list.php when clicking on one of the modules (summaryFull.php) show the old module name in the URL. It would be better to eliminate this name everywhere to avoid confusion.

Thanks,
Petra

**Comment by khan62** [comment]
The new module name is in the URLs now. Either name can be entered by hand, (e.g.
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=P-A-3-41
and
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/bbm.php?name=M_FR_914
direct to the same page)
but the database navigates using the new name.
