### ISSUE TITLE
Bad bump fraction per module

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#80]
Hello,
could we add a field on the top of the module test results page (near the grade) with a number = bad bumps on all ROCs / (16*4160) ?

Thanks,
Petra

**Comment by gneeser** [comment]
Petra, 
Which should I include in the count of bad bumps? Of course we have electrically bad bumps, X-ray bad bumps, reverse bias bad bumps, dead pixels, unaddressable pixels and unmaskable pixels. 

Do you just want the same four as are used in grading (electrically bad bumps, dead pixels, unaddressable pixels, and unmaskable pixels)?

**Comment by merkelp** [comment]
Hi,
I am only interested in the number of electrically bad bumps.

Thanks,
Petra

**Comment by gneeser** [comment]
Added text for the percent electrically bad bumps at the top of the page. Displays "No Data" if the field is null. Let me know if you spot any problems, otherwise I think we can close the issue.

**Comment by merkelp** [comment]
Hi, looks good for now.

Thanks,
Petra
