### ISSUE TITLE
No test results for P-A-3-43

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#81]
Hello,
can someone upload test results for this module? There is nothing but the IV.
At least bad bump counts would be good.

Thanks,
Petra

**Comment by jstupak** [comment]
This module doesn't work.  I forget exactly what the symptom is, but its in the "to be debugged" shelf at SiDet.

**Comment by NickHinton** [comment]
Given what John said, should I close this issue?

**Comment by merkelp** [comment]
Hello,
yes, that's fine. It brings up another point though. Maybe we could 
include some kind of flag for each module, that is set to one of the 
following options from a pull down menu:

1) fully tested --> ready to be mounted on half disk (if Grade=A)
2) to be tested (this could be the default it is set to when it gets 
shipped from the assembly centers)
3) to be x-rayed
4) to be debugged

Petra

**Comment by NickHinton** [comment]
Greg has opened a new issue to address your concern, Petra. I'm going to close this issue accordingly.
