### ISSUE TITLE
Tested module status flag

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb#84]
Adding new issue in response to Petra's comment:

Hello,
yes, that's fine. It brings up another point though. Maybe we could
include some kind of flag for each module, that is set to one of the
following options from a pull down menu:
…

1) fully tested --> ready to be mounted on half disk (if Grade=A)
2) to be tested (this could be the default it is set to when it gets
shipped from the assembly centers)
3) to be x-rayed
4) to be debugged

Petra

Our current plan is to add a field in "Manual Update" on the Full Test Summary page. We also plan to include this field in batch submit. 
-Greg

**Comment by gneeser** [comment]
I've added the flag in the database as FNAL Testing Status, visible on the Full Test Summary page. The value is not set for any module except for P-A-3-43, which is set to "To Be Debugged." The field can be modified on a per-module basis using the Manual Update option on the same page. We're still working towards a batch submit option, defaulting to the "To Be Tested" flag.

**Comment by gneeser** [comment]
Here's a question: do we want a batch submit option? To my understanding, using the Batch Full Test Submit should not automatically set the module to "Fully Tested" for example. That determination would have to be made by an expert after looking at the results, correct? 

In this case, do we want each module to have to be set manually to the appropriate testing status? 

This would be other than the default being set to "To Be Tested" upon being shipped to FNAL, of course.

-Greg

**Comment by merkelp** [comment]
Hello,
I think it would be a good idea to keep it manually, such that an expert 
has to do a final sign-off so to say.

Thanks,
Petra

**Comment by gneeser** [comment]
Before the module is promoted to shipped, the testing status is not set; upon being promoted to shipped, the FNAL testing status flag is set to "To Be Tested." Changes to this status must be made via the Manual Update forms on the Full Test Summary page.
