### ISSUE TITLE
Grade not based on FNAL results?

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#85]
Hello, at least for module P-A-2-20 the IV grade does not seem to be based on the Fermilab result, but on the Purdue measurements:
http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-2-20

Is this an oversight or a bug?

**Comment by NickHinton** [comment]
I think this is a bug, because module P-A-2-07 is grading based on Fermilab results (passed at Nebraska, Failed at Fermi, IV grade is C). 

http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-2-07

We'll have to dig into this issue.

**Comment by khan62** [comment]
I think I found the issue. The grade is based on the worst IV scan of the Bare Module, Fully Assembled Module, and FNAL measurement. Should it be set up instead such that later measurements supercede previous ones? I.e. FNAL trumps Fully Assembled trumps Bare Module

**Comment by NickHinton** [comment]
I think we do want the most recent measurement to be the 'official' measurement. 

Petra, what do you think?

**Comment by khan62** [comment]
The grade is now exclusively based on the trumping sequence, rather than the worst of the three. I think this will produce the results you expect.
