### ISSUE TITLE
Fermilab IV plot units

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#86]
Hello,
it seems that the units on the IV plot uploaded from Fermilab are wrong.
At least for this module: http://www.physics.purdue.edu/cmsfpix/Submission_p/summary/summaryFull.php?name=P-A-3-14
(first plot), the units should be A and not uA I think.

**Comment by khan62** [comment]
If you're referring to this plot:
http://www.physics.purdue.edu/cmsfpix/Submission_p/pics/sidet_p/sidet_p203pic0.jpg
That's a picture submitted by someone at Fermilab, so it'd have to be handled on their end. If necessary, I can replace it with a proper picture.

**Comment by NickHinton** [comment]
If there is no objection I'm going to mark this issue as closed later today, as it is not a problem with the DB but an issue with what is uploaded.

**Comment by merkelp** [comment]
Hi Nick,

that is ok. I cc John here, maybe he can take a look at it?
John, it seems that the IV plot that gets uploaded has the wrong units 
on the y-axis (uA instead of A).

Thanks,
Petra

**Comment by jstupak** [comment]
I fixed this, but only new uploads will be effected

**Comment by merkelp** [comment]
Thanks John, that's fine!

Petra
