### ISSUE TITLE
Removal of P---00 Parts from DB

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#87]
I'd like to fix the module names for the parts that are listed as P---00 in the DB. These are artifacts from switching naming conventions, so we should clean them up.

**Comment by khan62** [comment]
Do we just want them to only follow the sensor-based naming convention, rather than having an HDI-based name?

**Comment by NickHinton** [comment]
For those select modules, yes. All other modules that have a correct HDI-based name should continue to use that name.

**Comment by khan62** [comment]
All of the "P---00" modules now display as their module-based names.
