### ISSUE TITLE
Manual Module Submit Broken

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#88]
I was trying to manually add a few test modules, and when I hit submit I got a blank page at the following URL: http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/modulesubmit_proc.php

I was trying to add BL_TT_980 when it happened. Could this issue be related to the check against duplicating modules with the batch upload?

**Comment by khan62** [comment]
This was actually something I fixed in the test environment last week, but I wasn't able to log into clyde so I never pushed the changes to Submission_p. I just pushed the changes; see if it works now.

**Comment by NickHinton** [comment]
It worked. Thanks!
