### ISSUE TITLE
HDI Naming/Promotion Issue 2.0

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#89]
I added the last 5 batches of HDI to the DB through the new work order submit function. The names and order of the new batches can be found in the attached file.

I expected batch 3, YHD27-1015 to give modules named as P-C-x-yy, but instead got module P-I-x-yy. I promoted another module which ended up as P-J-x-yy instead of P-D-x-yy. Prior to adding the new batches I checked and only YHC69-1015 and YHD19-1815 were available in the drop-down menu for single HDI submit. So I'm confused as to why the module had I as the batch code instead of C (skipping 6 batches), or why if there were additional batches already in the DB they were not visible when submitting single HDI.

[Updated Naming Convention Doc 220151020.pdf](https://github.com/puhep/pudb/files/17048/Updated.Naming.Convention.Doc.220151020.pdf)

**Comment by khan62** [comment]
Looking at the MySQL database, it doesn't look like there's any reason why the incremeter skipped 3 through 8. I changed the work orders to their proper order (1 through 8) and reset the incrementer so it should pick up at 9.

**Comment by khan62** [comment]
I have also updated the modules to their proper names

**Comment by NickHinton** [comment]
I just promoted another part, P-F-test10-test10. It has a YFC67-2915 HDI, so I expect it to be P-E-test10-test10. Still 1 off...

**Comment by khan62** [comment]
I'm sorry, that was entirely my fault. I don't know why I offset them, but they're fixed now.

**Comment by NickHinton** [comment]
Looks good now, thanks!
