### ISSUE TITLE
Module mounted on disk

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#90]
Hi,
it would be very good if we could add another status possibility: mounted on disk.
In addition to this status, we should add by hand the disk number and the position on the disk. 
Then it would be great if this status was something we could search for: list all modules that have status=mounted on disk, and then a list of all those modules with their disk# and position.

Would this be feasible?
Thanks,
Petra

**Comment by merkelp** [comment]
Basically, if we could have on this page: http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/status.php
in the module table, a new column "Mounted" between "Shipped" and "Total", and when we click on the column header, we get the same table as under "Shipped", just with one more column listing the comment about disk number and position.

**Comment by NickHinton** [comment]
Hi Petra,

Could you provide us with the naming convention for disk numbers and positions on disk?
