### ISSUE TITLE
Addition of testing flags

### ISSUE THREAD

**Issue by lantone** [puhep/pudb#92]
We’d like to add flags to the database to mark that a module has completed each step of post-assembly testing.  These steps are the following:

```
Full test at 17C
Full test at -20C
X-ray testing
Thermal cycling
```

We envision these flags being set manually by the shifters once the testing has been performed.  

Additionally, we think what is currently the “FNAL Testing Status” would be best used by the experts to specify the next test scheduled for the module.  To this end, we propose changing its title to “Next Testing Step”, having the possible statuses being the following:

```
Full test at 17C
Full test at -20C
X-ray testing
Thermal cycling
Debugging
```

We envision these flags being set by experts who make the decision which of these steps will be performed for the given module and in which order.  Having this status searchable in the database will allow us to quickly get a global picture of the testing status and organize our testing efforts.

Thanks,

Jamie

**Comment by NickHinton** [comment]
In addition to the 5 options for the "Next Testing Step" I'd suggest we add 'Ready for Mounting'. This would replace the current 'fully tested' status and add the module to a 'Ready for Mounting' bin on the assembly status page (and address Petra's open issue).

Any objection from the Fermilab crew?

**Comment by lantone** [comment]
Good thinking!  Cecilia just requested the same thing in a separate discussion.  However, not _all_ fully tested modules will be mounted.  Maybe we want an additional status for fully tested modules that have grades too low to be mounted?  Maybe "Rejected" or similar?

**Comment by gneeser** [comment]
All,
I've implemented a number of the changes we discussed and wanted to let you take a look before Monday's meeting. 

We've changed "FNAL Testing Status" to "Next Testing Step." This can be seen on the Full Test Submission page in the test version of the DB here: 
http://www.physics.purdue.edu/cmsfpix/Submission_t/submit/fullSubmit.php?name=P-A-3-43 

The Next Testing Step can be set to the following values:
Full test at 17C
Full test at -20C
X-ray testing
Thermal cycling
Debugging
Ready for Mounting
Rejected

A couple of notes about some of the steps. Setting the Next Testing Step to "Ready for Mounting" will promote the module to the "Ready for Mounting" assembly step, visible here:
http://www.physics.purdue.edu/cmsfpix/Submission_t/assembly/status.php? 
Only modules that have the "Ready for Mounting" assembly status are eligible to be promoted to "On Blade."

Modules that have the "Rejected" Next Testing Step may still later be promoted to "Ready for Mounting" if, for example, our criterion are relaxed. 

Further, it should be noted that any changes submitted on the Full Test Submission page require the user field to be filled. Making changes to the Next Testing Step generates comments that include the user name. 

The Next Testing Step flag is searchable on the Tested Modules List page.

The post-assembly testing flags are coming soon, and it should also be noted that while changes are being made, parts of the test version of the site may not be functional.

**Comment by lantone** [comment]
Nice work!  IMHO those extra sorting options make the summary page _significantly_ more useful:

http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/test_list.php

Everything looks good to me, others should feel free to comment (that reminds I should make sure all the relevant people are subscribed to issues for this repo).

Thanks,
Jamie

**Comment by khan62** [comment]
The post-assembly testing flags are now implemented. They appear as a set of checkboxes on the Full Test Summary and Full Test Submission pages, but they are only editable from the Full Test Submission page. 

Example page:
http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/summaryFull.php?name=P-B-99-09

Next step is to make the status of those boxes searchable.

**Comment by khan62** [comment]
The post-assembly testing flags are now searchable on the Tested Module List page.

http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/test_list.php?

It will filter for modules that have completed at least the searched-for tests.
Example: If you filter for tests 1 and 3, you may also get modules that have completed tests 1, 3, and 4, but not a module that has only completed tests 1 and 2.
