### ISSUE TITLE
Additional User Name Fields

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#93]
Where are specific spots in the DB where we would like to require users to input their names? If there are must-have locations please let us know.

**Comment by NickHinton** [comment]
@lantone @merkelp

Forgot to tag folks on this...

**Comment by lantone** [comment]
Hi Nick, sorry, I didn't realize this was a separate issue from the previous one until just now.  It sounds like already implemented this for the full test submission page.  The other place that could use it is the location (or bonder) update pages, e.g.:
http://www.physics.purdue.edu/cmsfpix/Submission_t/submit/updatelocation.php?name=P-A-2-43

The best case scenario is that every piece of user-submitted information on the DB would have a name attached (but maybe that's a bit much to ask).  Here are two more places I found that it'd be useful to have a person held accountable (lower priority than the above):

http://www.physics.purdue.edu/cmsfpix/Submission_t/assembly/bbm.php?name=P-B-4-02
http://www.physics.purdue.edu/cmsfpix/Submission_t/summary/summarycomment.php?part=module_p&id=140

Petra should feel free to comment.

Thanks,
Jamie

**Comment by NickHinton** [comment]
We have added a required user name everywhere we can think of. If you find any missing areas, please let us know.
