### ISSUE TITLE
Promoting a module to installed on blade

### ISSUE THREAD

**Issue by merkelp** [puhep/pudb#95]
Hi,
I was able to do this with this module:
http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/bbm.php?name=P-B-7-29
( a little annoying side effect was that after submitting this new status, the page just went blank and I had to double back to get anywhere).
There is no checkmark next to this new status.
It would be nice if the information of which disk and blade this was installed on was also visible on this page.

However, I was not able to do the same for another module:
http://www.physics.purdue.edu/cmsfpix/Submission_p/assembly/bbm.php?name=P-B-5-34
Is this because previous steps have not yet been done?

Thanks,
Petra

**Comment by merkelp** [comment]
and for this module I can not set the 'next testing step':
http://www.physics.purdue.edu/cmsfpix/Submission_p/submit/fullSubmit.php?name=P-B-4-06

**Comment by gneeser** [comment]
Petra, 
As for the second issue, setting the next testing step on P-B-4-06, I was able to set the next testing step. Were you logged in at the time? If so, did you enter your username? If the user field is not filled, the page will not apply any changes made. Adding error messages for items like that is on my to-do list. If you did do these things, then I'll take a closer look and try to see what could have happened.

For promoting P-B-5-34, your suspicion was correct. Unless the Next Testing Step is set to 'Ready for Mounting' (meaning that the assembly step is also 'Ready for Mounting') users are not able to promote the module to On Blade. This in turn cannot be set unless the module has been fully assembled - meaning that its assembly status must be 'shipped.'

I'll add a checkbox and see about the issue after submitting the new status. Further, I'll add the info about where the module is on blade. 

Best,
Greg

**Comment by merkelp** [comment]
Hi Greg,

**Comment by NickHinton** [comment]
Hi Petra,

We have not been able to replicate your problem on P-B-4-06. Both Greg and I were able to update the next testing status on different machines (and multiple modules). Can you try to replicate the failure?

The blank page that displays after updating a module's assembly status is a global issue that we are working on. However, we believe any submitted updates will be successful. 

Thanks,
Nick

**Comment by khan62** [comment]
The blank page issue has been fixed.

**Comment by merkelp** [comment]
Hi Nick,
I will try again, maybe I got logged out for some reason.

Thanks for checking,
Petra

**Comment by merkelp** [comment]
Hi, I tried again, and was now successful in mounting all four modules on blades.
I guess I had just gotten logged out due to some glitch, or lost internet connection or something.
Looks good now, thanks.
Petra
