### ISSUE TITLE
Need to Record ROC Thickness in DB

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb#97]
Due to an issue with the thinning of the ROCs on some production wafers, we will need to record the thicknesses of the ROC wafers in the DB. This parameter should be visible from the module's summary page (perhaps directly above the ROC table) and also be searchable.

**Comment by gneeser** [comment]
ROC thickness is now properly recorded and displayed in the database. Search functionality is pending.

**Comment by gneeser** [comment]
ROC thickness is now a searchable field on the tested modules list page.
